// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package acpcart

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BuyerAccountType.
const (
	BuyerAccountTypeBusiness   BuyerAccountType = "business"
	BuyerAccountTypeGuest      BuyerAccountType = "guest"
	BuyerAccountTypeRegistered BuyerAccountType = "registered"
)

// Valid indicates whether the value is a known member of the BuyerAccountType enum.
func (e BuyerAccountType) Valid() bool {
	switch e {
	case BuyerAccountTypeBusiness:
		return true
	case BuyerAccountTypeGuest:
		return true
	case BuyerAccountTypeRegistered:
		return true
	default:
		return false
	}
}

// Defines values for BuyerAuthenticationStatus.
const (
	BuyerAuthenticationStatusAuthenticated  BuyerAuthenticationStatus = "authenticated"
	BuyerAuthenticationStatusGuest          BuyerAuthenticationStatus = "guest"
	BuyerAuthenticationStatusRequiresSignin BuyerAuthenticationStatus = "requires_signin"
)

// Valid indicates whether the value is a known member of the BuyerAuthenticationStatus enum.
func (e BuyerAuthenticationStatus) Valid() bool {
	switch e {
	case BuyerAuthenticationStatusAuthenticated:
		return true
	case BuyerAuthenticationStatusGuest:
		return true
	case BuyerAuthenticationStatusRequiresSignin:
		return true
	default:
		return false
	}
}

// Defines values for DimensionsInfoUnit.
const (
	Cm DimensionsInfoUnit = "cm"
	In DimensionsInfoUnit = "in"
)

// Valid indicates whether the value is a known member of the DimensionsInfoUnit enum.
func (e DimensionsInfoUnit) Valid() bool {
	switch e {
	case Cm:
		return true
	case In:
		return true
	default:
		return false
	}
}

// Defines values for DisclosureContentType.
const (
	DisclosureContentTypeMarkdown DisclosureContentType = "markdown"
	DisclosureContentTypePlain    DisclosureContentType = "plain"
)

// Valid indicates whether the value is a known member of the DisclosureContentType enum.
func (e DisclosureContentType) Valid() bool {
	switch e {
	case DisclosureContentTypeMarkdown:
		return true
	case DisclosureContentTypePlain:
		return true
	default:
		return false
	}
}

// Defines values for DisclosureType.
const (
	Disclaimer DisclosureType = "disclaimer"
)

// Valid indicates whether the value is a known member of the DisclosureType enum.
func (e DisclosureType) Valid() bool {
	switch e {
	case Disclaimer:
		return true
	default:
		return false
	}
}

// Defines values for DiscountDetailSource.
const (
	Automatic DiscountDetailSource = "automatic"
	Coupon    DiscountDetailSource = "coupon"
	Loyalty   DiscountDetailSource = "loyalty"
)

// Valid indicates whether the value is a known member of the DiscountDetailSource enum.
func (e DiscountDetailSource) Valid() bool {
	switch e {
	case Automatic:
		return true
	case Coupon:
		return true
	case Loyalty:
		return true
	default:
		return false
	}
}

// Defines values for DiscountDetailType.
const (
	Bogo       DiscountDetailType = "bogo"
	Fixed      DiscountDetailType = "fixed"
	Percentage DiscountDetailType = "percentage"
	Volume     DiscountDetailType = "volume"
)

// Valid indicates whether the value is a known member of the DiscountDetailType enum.
func (e DiscountDetailType) Valid() bool {
	switch e {
	case Bogo:
		return true
	case Fixed:
		return true
	case Percentage:
		return true
	case Volume:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	InvalidRequest     ErrorType = "invalid_request"
	ProcessingError    ErrorType = "processing_error"
	ServiceUnavailable ErrorType = "service_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case InvalidRequest:
		return true
	case ProcessingError:
		return true
	case ServiceUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for LineItemAvailabilityStatus.
const (
	LineItemAvailabilityStatusBackorder  LineItemAvailabilityStatus = "backorder"
	LineItemAvailabilityStatusInStock    LineItemAvailabilityStatus = "in_stock"
	LineItemAvailabilityStatusLowStock   LineItemAvailabilityStatus = "low_stock"
	LineItemAvailabilityStatusOutOfStock LineItemAvailabilityStatus = "out_of_stock"
	LineItemAvailabilityStatusPreOrder   LineItemAvailabilityStatus = "pre_order"
)

// Valid indicates whether the value is a known member of the LineItemAvailabilityStatus enum.
func (e LineItemAvailabilityStatus) Valid() bool {
	switch e {
	case LineItemAvailabilityStatusBackorder:
		return true
	case LineItemAvailabilityStatusInStock:
		return true
	case LineItemAvailabilityStatusLowStock:
		return true
	case LineItemAvailabilityStatusOutOfStock:
		return true
	case LineItemAvailabilityStatusPreOrder:
		return true
	default:
		return false
	}
}

// Defines values for MessageErrorCode.
const (
	MessageErrorCodeAgeVerificationRequired MessageErrorCode = "age_verification_required"
	MessageErrorCodeApprovalRequired        MessageErrorCode = "approval_required"
	MessageErrorCodeConflict                MessageErrorCode = "conflict"
	MessageErrorCodeCouponExpired           MessageErrorCode = "coupon_expired"
	MessageErrorCodeCouponInvalid           MessageErrorCode = "coupon_invalid"
	MessageErrorCodeExpired                 MessageErrorCode = "expired"
	MessageErrorCodeInterventionRequired    MessageErrorCode = "intervention_required"
	MessageErrorCodeInvalid                 MessageErrorCode = "invalid"
	MessageErrorCodeLowStock                MessageErrorCode = "low_stock"
	MessageErrorCodeMaximumExceeded         MessageErrorCode = "maximum_exceeded"
	MessageErrorCodeMinimumNotMet           MessageErrorCode = "minimum_not_met"
	MessageErrorCodeMissing                 MessageErrorCode = "missing"
	MessageErrorCodeNotFound                MessageErrorCode = "not_found"
	MessageErrorCodeOutOfStock              MessageErrorCode = "out_of_stock"
	MessageErrorCodePaymentDeclined         MessageErrorCode = "payment_declined"
	MessageErrorCodeQuantityExceeded        MessageErrorCode = "quantity_exceeded"
	MessageErrorCodeRateLimited             MessageErrorCode = "rate_limited"
	MessageErrorCodeRegionRestricted        MessageErrorCode = "region_restricted"
	MessageErrorCodeRequires3ds             MessageErrorCode = "requires_3ds"
	MessageErrorCodeRequiresSignIn          MessageErrorCode = "requires_sign_in"
	MessageErrorCodeUnsupported             MessageErrorCode = "unsupported"
)

// Valid indicates whether the value is a known member of the MessageErrorCode enum.
func (e MessageErrorCode) Valid() bool {
	switch e {
	case MessageErrorCodeAgeVerificationRequired:
		return true
	case MessageErrorCodeApprovalRequired:
		return true
	case MessageErrorCodeConflict:
		return true
	case MessageErrorCodeCouponExpired:
		return true
	case MessageErrorCodeCouponInvalid:
		return true
	case MessageErrorCodeExpired:
		return true
	case MessageErrorCodeInterventionRequired:
		return true
	case MessageErrorCodeInvalid:
		return true
	case MessageErrorCodeLowStock:
		return true
	case MessageErrorCodeMaximumExceeded:
		return true
	case MessageErrorCodeMinimumNotMet:
		return true
	case MessageErrorCodeMissing:
		return true
	case MessageErrorCodeNotFound:
		return true
	case MessageErrorCodeOutOfStock:
		return true
	case MessageErrorCodePaymentDeclined:
		return true
	case MessageErrorCodeQuantityExceeded:
		return true
	case MessageErrorCodeRateLimited:
		return true
	case MessageErrorCodeRegionRestricted:
		return true
	case MessageErrorCodeRequires3ds:
		return true
	case MessageErrorCodeRequiresSignIn:
		return true
	case MessageErrorCodeUnsupported:
		return true
	default:
		return false
	}
}

// Defines values for MessageErrorContentType.
const (
	MessageErrorContentTypeMarkdown MessageErrorContentType = "markdown"
	MessageErrorContentTypePlain    MessageErrorContentType = "plain"
)

// Valid indicates whether the value is a known member of the MessageErrorContentType enum.
func (e MessageErrorContentType) Valid() bool {
	switch e {
	case MessageErrorContentTypeMarkdown:
		return true
	case MessageErrorContentTypePlain:
		return true
	default:
		return false
	}
}

// Defines values for MessageErrorResolution.
const (
	MessageErrorResolutionRecoverable         MessageErrorResolution = "recoverable"
	MessageErrorResolutionRequiresBuyerInput  MessageErrorResolution = "requires_buyer_input"
	MessageErrorResolutionRequiresBuyerReview MessageErrorResolution = "requires_buyer_review"
)

// Valid indicates whether the value is a known member of the MessageErrorResolution enum.
func (e MessageErrorResolution) Valid() bool {
	switch e {
	case MessageErrorResolutionRecoverable:
		return true
	case MessageErrorResolutionRequiresBuyerInput:
		return true
	case MessageErrorResolutionRequiresBuyerReview:
		return true
	default:
		return false
	}
}

// Defines values for MessageErrorSeverity.
const (
	MessageErrorSeverityCritical MessageErrorSeverity = "critical"
	MessageErrorSeverityHigh     MessageErrorSeverity = "high"
	MessageErrorSeverityInfo     MessageErrorSeverity = "info"
	MessageErrorSeverityLow      MessageErrorSeverity = "low"
	MessageErrorSeverityMedium   MessageErrorSeverity = "medium"
)

// Valid indicates whether the value is a known member of the MessageErrorSeverity enum.
func (e MessageErrorSeverity) Valid() bool {
	switch e {
	case MessageErrorSeverityCritical:
		return true
	case MessageErrorSeverityHigh:
		return true
	case MessageErrorSeverityInfo:
		return true
	case MessageErrorSeverityLow:
		return true
	case MessageErrorSeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for MessageErrorType.
const (
	MessageErrorTypeError MessageErrorType = "error"
)

// Valid indicates whether the value is a known member of the MessageErrorType enum.
func (e MessageErrorType) Valid() bool {
	switch e {
	case MessageErrorTypeError:
		return true
	default:
		return false
	}
}

// Defines values for MessageInfoContentType.
const (
	MessageInfoContentTypeMarkdown MessageInfoContentType = "markdown"
	MessageInfoContentTypePlain    MessageInfoContentType = "plain"
)

// Valid indicates whether the value is a known member of the MessageInfoContentType enum.
func (e MessageInfoContentType) Valid() bool {
	switch e {
	case MessageInfoContentTypeMarkdown:
		return true
	case MessageInfoContentTypePlain:
		return true
	default:
		return false
	}
}

// Defines values for MessageInfoResolution.
const (
	MessageInfoResolutionRecoverable         MessageInfoResolution = "recoverable"
	MessageInfoResolutionRequiresBuyerInput  MessageInfoResolution = "requires_buyer_input"
	MessageInfoResolutionRequiresBuyerReview MessageInfoResolution = "requires_buyer_review"
)

// Valid indicates whether the value is a known member of the MessageInfoResolution enum.
func (e MessageInfoResolution) Valid() bool {
	switch e {
	case MessageInfoResolutionRecoverable:
		return true
	case MessageInfoResolutionRequiresBuyerInput:
		return true
	case MessageInfoResolutionRequiresBuyerReview:
		return true
	default:
		return false
	}
}

// Defines values for MessageInfoSeverity.
const (
	MessageInfoSeverityCritical MessageInfoSeverity = "critical"
	MessageInfoSeverityHigh     MessageInfoSeverity = "high"
	MessageInfoSeverityInfo     MessageInfoSeverity = "info"
	MessageInfoSeverityLow      MessageInfoSeverity = "low"
	MessageInfoSeverityMedium   MessageInfoSeverity = "medium"
)

// Valid indicates whether the value is a known member of the MessageInfoSeverity enum.
func (e MessageInfoSeverity) Valid() bool {
	switch e {
	case MessageInfoSeverityCritical:
		return true
	case MessageInfoSeverityHigh:
		return true
	case MessageInfoSeverityInfo:
		return true
	case MessageInfoSeverityLow:
		return true
	case MessageInfoSeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for MessageInfoType.
const (
	MessageInfoTypeInfo MessageInfoType = "info"
)

// Valid indicates whether the value is a known member of the MessageInfoType enum.
func (e MessageInfoType) Valid() bool {
	switch e {
	case MessageInfoTypeInfo:
		return true
	default:
		return false
	}
}

// Defines values for MessageWarningCode.
const (
	MessageWarningCodeDiscountCodeAlreadyApplied        MessageWarningCode = "discount_code_already_applied"
	MessageWarningCodeDiscountCodeCombinationDisallowed MessageWarningCode = "discount_code_combination_disallowed"
	MessageWarningCodeDiscountCodeExpired               MessageWarningCode = "discount_code_expired"
	MessageWarningCodeDiscountCodeInvalid               MessageWarningCode = "discount_code_invalid"
	MessageWarningCodeDiscountCodeMinimumNotMet         MessageWarningCode = "discount_code_minimum_not_met"
	MessageWarningCodeDiscountCodeUsageLimitReached     MessageWarningCode = "discount_code_usage_limit_reached"
	MessageWarningCodeDiscountCodeUserIneligible        MessageWarningCode = "discount_code_user_ineligible"
	MessageWarningCodeDiscountCodeUserNotLoggedIn       MessageWarningCode = "discount_code_user_not_logged_in"
	MessageWarningCodeExpiringPromotion                 MessageWarningCode = "expiring_promotion"
	MessageWarningCodeHighDemand                        MessageWarningCode = "high_demand"
	MessageWarningCodeLimitedAvailability               MessageWarningCode = "limited_availability"
	MessageWarningCodeLowStock                          MessageWarningCode = "low_stock"
	MessageWarningCodePriceChange                       MessageWarningCode = "price_change"
	MessageWarningCodeShippingDelay                     MessageWarningCode = "shipping_delay"
)

// Valid indicates whether the value is a known member of the MessageWarningCode enum.
func (e MessageWarningCode) Valid() bool {
	switch e {
	case MessageWarningCodeDiscountCodeAlreadyApplied:
		return true
	case MessageWarningCodeDiscountCodeCombinationDisallowed:
		return true
	case MessageWarningCodeDiscountCodeExpired:
		return true
	case MessageWarningCodeDiscountCodeInvalid:
		return true
	case MessageWarningCodeDiscountCodeMinimumNotMet:
		return true
	case MessageWarningCodeDiscountCodeUsageLimitReached:
		return true
	case MessageWarningCodeDiscountCodeUserIneligible:
		return true
	case MessageWarningCodeDiscountCodeUserNotLoggedIn:
		return true
	case MessageWarningCodeExpiringPromotion:
		return true
	case MessageWarningCodeHighDemand:
		return true
	case MessageWarningCodeLimitedAvailability:
		return true
	case MessageWarningCodeLowStock:
		return true
	case MessageWarningCodePriceChange:
		return true
	case MessageWarningCodeShippingDelay:
		return true
	default:
		return false
	}
}

// Defines values for MessageWarningContentType.
const (
	MessageWarningContentTypeMarkdown MessageWarningContentType = "markdown"
	MessageWarningContentTypePlain    MessageWarningContentType = "plain"
)

// Valid indicates whether the value is a known member of the MessageWarningContentType enum.
func (e MessageWarningContentType) Valid() bool {
	switch e {
	case MessageWarningContentTypeMarkdown:
		return true
	case MessageWarningContentTypePlain:
		return true
	default:
		return false
	}
}

// Defines values for MessageWarningResolution.
const (
	MessageWarningResolutionRecoverable         MessageWarningResolution = "recoverable"
	MessageWarningResolutionRequiresBuyerInput  MessageWarningResolution = "requires_buyer_input"
	MessageWarningResolutionRequiresBuyerReview MessageWarningResolution = "requires_buyer_review"
)

// Valid indicates whether the value is a known member of the MessageWarningResolution enum.
func (e MessageWarningResolution) Valid() bool {
	switch e {
	case MessageWarningResolutionRecoverable:
		return true
	case MessageWarningResolutionRequiresBuyerInput:
		return true
	case MessageWarningResolutionRequiresBuyerReview:
		return true
	default:
		return false
	}
}

// Defines values for MessageWarningSeverity.
const (
	MessageWarningSeverityCritical MessageWarningSeverity = "critical"
	MessageWarningSeverityHigh     MessageWarningSeverity = "high"
	MessageWarningSeverityInfo     MessageWarningSeverity = "info"
	MessageWarningSeverityLow      MessageWarningSeverity = "low"
	MessageWarningSeverityMedium   MessageWarningSeverity = "medium"
)

// Valid indicates whether the value is a known member of the MessageWarningSeverity enum.
func (e MessageWarningSeverity) Valid() bool {
	switch e {
	case MessageWarningSeverityCritical:
		return true
	case MessageWarningSeverityHigh:
		return true
	case MessageWarningSeverityInfo:
		return true
	case MessageWarningSeverityLow:
		return true
	case MessageWarningSeverityMedium:
		return true
	default:
		return false
	}
}

// Defines values for MessageWarningType.
const (
	Warning MessageWarningType = "warning"
)

// Valid indicates whether the value is a known member of the MessageWarningType enum.
func (e MessageWarningType) Valid() bool {
	switch e {
	case Warning:
		return true
	default:
		return false
	}
}

// Defines values for TaxExemptionCertificateType.
const (
	ExemptOrganization TaxExemptionCertificateType = "exempt_organization"
	Government         TaxExemptionCertificateType = "government"
	Resale             TaxExemptionCertificateType = "resale"
)

// Valid indicates whether the value is a known member of the TaxExemptionCertificateType enum.
func (e TaxExemptionCertificateType) Valid() bool {
	switch e {
	case ExemptOrganization:
		return true
	case Government:
		return true
	case Resale:
		return true
	default:
		return false
	}
}

// Defines values for TotalType.
const (
	TotalTypeAmountRefunded  TotalType = "amount_refunded"
	TotalTypeDiscount        TotalType = "discount"
	TotalTypeFee             TotalType = "fee"
	TotalTypeFulfillment     TotalType = "fulfillment"
	TotalTypeGiftWrap        TotalType = "gift_wrap"
	TotalTypeItemsBaseAmount TotalType = "items_base_amount"
	TotalTypeItemsDiscount   TotalType = "items_discount"
	TotalTypeStoreCredit     TotalType = "store_credit"
	TotalTypeSubtotal        TotalType = "subtotal"
	TotalTypeTax             TotalType = "tax"
	TotalTypeTip             TotalType = "tip"
	TotalTypeTotal           TotalType = "total"
)

// Valid indicates whether the value is a known member of the TotalType enum.
func (e TotalType) Valid() bool {
	switch e {
	case TotalTypeAmountRefunded:
		return true
	case TotalTypeDiscount:
		return true
	case TotalTypeFee:
		return true
	case TotalTypeFulfillment:
		return true
	case TotalTypeGiftWrap:
		return true
	case TotalTypeItemsBaseAmount:
		return true
	case TotalTypeItemsDiscount:
		return true
	case TotalTypeStoreCredit:
		return true
	case TotalTypeSubtotal:
		return true
	case TotalTypeTax:
		return true
	case TotalTypeTip:
		return true
	case TotalTypeTotal:
		return true
	default:
		return false
	}
}

// Defines values for WeightInfoUnit.
const (
	G  WeightInfoUnit = "g"
	Kg WeightInfoUnit = "kg"
	Lb WeightInfoUnit = "lb"
	Oz WeightInfoUnit = "oz"
)

// Valid indicates whether the value is a known member of the WeightInfoUnit enum.
func (e WeightInfoUnit) Valid() bool {
	switch e {
	case G:
		return true
	case Kg:
		return true
	case Lb:
		return true
	case Oz:
		return true
	default:
		return false
	}
}

// Buyer Information about the buyer including contact details, company info, and loyalty status
type Buyer struct {
	// AccountType Type of buyer account
	AccountType *BuyerAccountType `json:"account_type,omitempty"`

	// AuthenticationStatus Buyer's authentication status
	AuthenticationStatus *BuyerAuthenticationStatus `json:"authentication_status,omitempty"`

	// Company Company information for business buyers
	Company *CompanyInfo `json:"company,omitempty"`

	// CustomerId Merchant's internal customer identifier
	CustomerId *string `json:"customer_id,omitempty"`

	// Email Buyer's email address
	Email openapi_types.Email `json:"email"`

	// FirstName Buyer's first name
	FirstName *string `json:"first_name,omitempty"`

	// FullName Buyer's full name
	FullName *string `json:"full_name,omitempty"`

	// LastName Buyer's last name
	LastName *string `json:"last_name,omitempty"`

	// Loyalty Loyalty program information
	Loyalty *LoyaltyInfo `json:"loyalty,omitempty"`

	// PhoneNumber Buyer's phone number
	PhoneNumber *string `json:"phone_number,omitempty"`

	// TaxExemption Tax exemption details
	TaxExemption *TaxExemption `json:"tax_exemption,omitempty"`
}

// BuyerAccountType Type of buyer account
type BuyerAccountType string

// BuyerAuthenticationStatus Buyer's authentication status
type BuyerAuthenticationStatus string

// Cart A shopping cart with estimated pricing. Carts provide a lightweight pre-checkout phase for item collection without payment configuration or status lifecycle.
type Cart struct {
	// Buyer Buyer information, if provided.
	Buyer *Buyer `json:"buyer,omitempty"`

	// ContinueUrl URL for cart handoff, sharing, or session recovery.
	ContinueUrl *string `json:"continue_url,omitempty"`

	// Currency ISO 4217 currency code. Determined by the seller based on context or request.
	Currency string `json:"currency"`

	// ExpiresAt RFC 3339 timestamp when the cart expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Id Unique cart identifier, server-generated.
	Id string `json:"id"`

	// LineItems Cart line items. Same structure as checkout line items.
	LineItems []LineItem `json:"line_items"`

	// Messages Validation messages, warnings, or informational notices (e.g., low stock, price changes).
	Messages *[]Cart_Messages_Item `json:"messages,omitempty"`

	// Totals Estimated cost breakdown. May be partial (e.g., tax omitted if address is unknown). Totals are estimates until checkout.
	Totals []Total `json:"totals"`
}

// Cart_Messages_Item defines model for Cart.messages.Item.
type Cart_Messages_Item struct {
	union json.RawMessage
}

// CartCreateRequest Request to create a new cart.
type CartCreateRequest struct {
	// Buyer Buyer information for personalized estimates.
	Buyer *Buyer `json:"buyer,omitempty"`

	// LineItems Items to add to the cart.
	LineItems []Item `json:"line_items"`

	// Locale Locale code for content localization (e.g., 'en-US').
	Locale *string `json:"locale,omitempty"`
}

// CartUpdateRequest Request to update a cart. Full replacement — the agent MUST send the complete desired cart state.
type CartUpdateRequest struct {
	// Buyer Updated buyer information.
	Buyer *Buyer `json:"buyer,omitempty"`

	// LineItems Complete list of items (replaces existing cart contents).
	LineItems []Item `json:"line_items"`
}

// CompanyInfo Information about a company or organization associated with the buyer
type CompanyInfo struct {
	// CostCenter Cost center code for internal accounting
	CostCenter *string `json:"cost_center,omitempty"`

	// Department Department within the organization
	Department *string `json:"department,omitempty"`

	// Name Company or organization name
	Name string `json:"name"`

	// TaxId Business tax identification number
	TaxId *string `json:"tax_id,omitempty"`
}

// CustomAttribute Custom key-value attribute for merchant-specific metadata on line items
type CustomAttribute struct {
	// DisplayName Human-readable label for the attribute
	DisplayName string `json:"display_name"`

	// Value Attribute value
	Value string `json:"value"`
}

// DimensionsInfo Physical dimensions of a product with unit of measurement
type DimensionsInfo struct {
	// Height Height dimension
	Height float32 `json:"height"`

	// Length Length dimension
	Length float32 `json:"length"`

	// Unit Unit of measurement for dimensions
	Unit DimensionsInfoUnit `json:"unit"`

	// Width Width dimension
	Width float32 `json:"width"`
}

// DimensionsInfoUnit Unit of measurement for dimensions
type DimensionsInfoUnit string

// Disclosure Legal disclosure or terms that must be acknowledged by the buyer
type Disclosure struct {
	// Content The disclosure text content. When content_type is 'markdown', this MUST be valid CommonMark with no raw HTML. Agents MUST render using a CommonMark-compliant parser with raw HTML output disabled or sanitized.
	Content string `json:"content"`

	// ContentType Format of the disclosure content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
	ContentType DisclosureContentType `json:"content_type"`

	// Type Type of disclosure
	Type DisclosureType `json:"type"`
}

// DisclosureContentType Format of the disclosure content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
type DisclosureContentType string

// DisclosureType Type of disclosure
type DisclosureType string

// DiscountDetail Information about a discount applied to the checkout or a specific item
type DiscountDetail struct {
	// Amount Discount amount in minor currency units (e.g. 100 cents for $1.00 or 100 for ¥100)
	Amount int `json:"amount"`

	// Code Discount code if applicable
	Code *string `json:"code,omitempty"`

	// Description Human-readable discount description
	Description *string `json:"description,omitempty"`

	// Source Source of the discount
	Source *DiscountDetailSource `json:"source,omitempty"`

	// Type Type of discount
	Type DiscountDetailType `json:"type"`
}

// DiscountDetailSource Source of the discount
type DiscountDetailSource string

// DiscountDetailType Type of discount
type DiscountDetailType string

// Error Protocol-level error returned in 4xx/5xx responses when the server cannot return a valid CheckoutSession at all (e.g. malformed request or unexpected failure). Use Error—not MessageError—when there is no valid session state to return. type semantics: invalid_request — malformed request, missing required fields, invalid JSON, or idempotency violations (codes: idempotency_key_required, idempotency_in_flight, idempotency_conflict); processing_error — unexpected server-side failure; service_unavailable — temporary unavailability.
type Error struct {
	// Code Implementation-defined error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Param RFC 9535 JSONPath (optional)
	Param *string `json:"param,omitempty"`

	// SupportedVersions List of API versions supported by the server, ordered by preference (newest first). Only included in version-related errors.
	SupportedVersions *[]string `json:"supported_versions,omitempty"`

	// Type Error type indicating the category of protocol-level error
	Type ErrorType `json:"type"`
}

// ErrorType Error type indicating the category of protocol-level error
type ErrorType string

// Item A purchasable item with variant options (e.g., size, color) and quantity
type Item struct {
	// Id Unique identifier for the item
	Id string `json:"id"`

	// Name Display name of the item
	Name *string `json:"name,omitempty"`

	// UnitAmount Price per unit in minor currency units (e.g. 100 cents for $1.00 or 100 for ¥100)
	UnitAmount *int `json:"unit_amount,omitempty"`
}

// LineItem A line item in the checkout representing a product with pricing, discounts, and fulfillment details
type LineItem struct {
	// AvailabilityStatus Current availability status of the item
	AvailabilityStatus *LineItemAvailabilityStatus `json:"availability_status,omitempty"`

	// AvailableQuantity Quantity currently available for purchase
	AvailableQuantity *int `json:"available_quantity,omitempty"`

	// Category Product category
	Category *string `json:"category,omitempty"`

	// CustomAttributes Custom attributes specific to this line item
	CustomAttributes *[]CustomAttribute `json:"custom_attributes,omitempty"`

	// Description Detailed description of the line item
	Description *string `json:"description,omitempty"`

	// Dimensions Dimensions for the item
	Dimensions *DimensionsInfo `json:"dimensions,omitempty"`

	// Disclosures Legal disclosures or disclaimers for this item
	Disclosures *[]Disclosure `json:"disclosures,omitempty"`

	// DiscountDetails Line-item level discount details
	DiscountDetails *[]DiscountDetail `json:"discount_details,omitempty"`

	// FulfillableOn RFC 3339 timestamp when item becomes available for fulfillment
	FulfillableOn *time.Time `json:"fulfillable_on,omitempty"`

	// Id Unique identifier for the line item
	Id string `json:"id"`

	// Images Array of image URLs for this line item
	Images *[]string `json:"images,omitempty"`

	// Item Reference to the item being purchased
	Item Item `json:"item"`

	// MarketplaceSellerDetails Seller details for marketplace items
	MarketplaceSellerDetails *MarketplaceSellerDetails `json:"marketplace_seller_details,omitempty"`

	// MaxQuantityPerOrder Maximum quantity allowed per order
	MaxQuantityPerOrder *int `json:"max_quantity_per_order,omitempty"`

	// Name Display name of the line item
	Name *string `json:"name,omitempty"`

	// ParentId Reference to parent line item for bundled products
	ParentId *string `json:"parent_id,omitempty"`

	// ProductId Merchant's product identifier
	ProductId *string `json:"product_id,omitempty"`

	// Quantity Number of units for this line item
	Quantity int `json:"quantity"`

	// Sku Stock keeping unit identifier
	Sku *string `json:"sku,omitempty"`

	// Tags Product tags or labels
	Tags *[]string `json:"tags,omitempty"`

	// TaxExempt Whether this line item is tax exempt
	TaxExempt *bool `json:"tax_exempt,omitempty"`

	// TaxExemptionReason Reason for tax exemption if applicable
	TaxExemptionReason *string `json:"tax_exemption_reason,omitempty"`

	// Totals Line-item level totals breakdown including base_amount, discount, subtotal, tax, and total
	Totals []Total `json:"totals"`

	// UnitAmount The unit price of the line item in the smallest currency unit (e.g., cents for USD)
	UnitAmount *int `json:"unit_amount,omitempty"`

	// VariantId Product variant identifier
	VariantId *string `json:"variant_id,omitempty"`

	// VariantOptions Selected product variant options (e.g., size, color)
	VariantOptions *[]VariantOption `json:"variant_options,omitempty"`

	// Weight Weight information for the item
	Weight *WeightInfo `json:"weight,omitempty"`
}

// LineItemAvailabilityStatus Current availability status of the item
type LineItemAvailabilityStatus string

// LoyaltyInfo Loyalty program information including membership details and rewards balance
type LoyaltyInfo struct {
	// MemberSince RFC 3339 timestamp when the customer joined the loyalty program
	MemberSince *time.Time `json:"member_since,omitempty"`

	// PointsBalance Current loyalty points balance
	PointsBalance *int `json:"points_balance,omitempty"`

	// Tier Loyalty program tier level
	Tier *string `json:"tier,omitempty"`
}

// MarketplaceSellerDetails Information about a third-party seller in a marketplace model
type MarketplaceSellerDetails struct {
	// Name Name of the marketplace seller or vendor
	Name string `json:"name"`
}

// MessageError Business-logic error within a valid CheckoutSession response. Used in messages[] on 2xx responses when the session is valid but has actionable issues (e.g. status "not_ready_for_payment"). The agent can respond by asking the buyer for corrections or trying alternatives. Use MessageError—not Error—when you can return a valid CheckoutSession and the problem is conversational (e.g. invalid email → code "invalid" and param "$.buyer.email"; out of stock → code "out_of_stock" and param "$.items[0]").
type MessageError struct {
	// Code Error code indicating the type of error
	Code MessageErrorCode `json:"code"`

	// Content Error message text. When content_type is 'markdown', this MUST be valid CommonMark with no raw HTML. Agents MUST render using a CommonMark-compliant parser with raw HTML output disabled or sanitized.
	Content string `json:"content"`

	// ContentType Format of the error message content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
	ContentType MessageErrorContentType `json:"content_type"`

	// Param RFC 9535 JSONPath
	Param *string `json:"param,omitempty"`

	// Resolution Who resolves this message. 'recoverable': agent can fix via API. 'requires_buyer_input': buyer must provide info. 'requires_buyer_review': buyer must authorize.
	Resolution *MessageErrorResolution `json:"resolution,omitempty"`

	// Severity Severity level of this error
	Severity *MessageErrorSeverity `json:"severity,omitempty"`

	// Type Message type discriminator
	Type MessageErrorType `json:"type"`
}

// MessageErrorCode Error code indicating the type of error
type MessageErrorCode string

// MessageErrorContentType Format of the error message content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
type MessageErrorContentType string

// MessageErrorResolution Who resolves this message. 'recoverable': agent can fix via API. 'requires_buyer_input': buyer must provide info. 'requires_buyer_review': buyer must authorize.
type MessageErrorResolution string

// MessageErrorSeverity Severity level of this error
type MessageErrorSeverity string

// MessageErrorType Message type discriminator
type MessageErrorType string

// MessageInfo Informational message to display to the buyer during checkout
type MessageInfo struct {
	// Content Informational message text. When content_type is 'markdown', this MUST be valid CommonMark with no raw HTML. Agents MUST render using a CommonMark-compliant parser with raw HTML output disabled or sanitized.
	Content string `json:"content"`

	// ContentType Format of the message content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
	ContentType MessageInfoContentType `json:"content_type"`

	// Param RFC 9535 JSONPath
	Param *string `json:"param,omitempty"`

	// Resolution Who resolves this message. 'recoverable': agent can fix via API. 'requires_buyer_input': buyer must provide info. 'requires_buyer_review': buyer must authorize.
	Resolution *MessageInfoResolution `json:"resolution,omitempty"`

	// Severity Severity level of this informational message
	Severity *MessageInfoSeverity `json:"severity,omitempty"`

	// Type Message type discriminator
	Type MessageInfoType `json:"type"`
}

// MessageInfoContentType Format of the message content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
type MessageInfoContentType string

// MessageInfoResolution Who resolves this message. 'recoverable': agent can fix via API. 'requires_buyer_input': buyer must provide info. 'requires_buyer_review': buyer must authorize.
type MessageInfoResolution string

// MessageInfoSeverity Severity level of this informational message
type MessageInfoSeverity string

// MessageInfoType Message type discriminator
type MessageInfoType string

// MessageWarning Warning message to display to the buyer during checkout (non-blocking)
type MessageWarning struct {
	// Code Warning code indicating the type of warning
	Code MessageWarningCode `json:"code"`

	// Content Warning message text. When content_type is 'markdown', this MUST be valid CommonMark with no raw HTML. Agents MUST render using a CommonMark-compliant parser with raw HTML output disabled or sanitized.
	Content string `json:"content"`

	// ContentType Format of the warning message content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
	ContentType MessageWarningContentType `json:"content_type"`

	// Param RFC 9535 JSONPath
	Param *string `json:"param,omitempty"`

	// Resolution Who resolves this message. 'recoverable': agent can fix via API. 'requires_buyer_input': buyer must provide info. 'requires_buyer_review': buyer must authorize.
	Resolution *MessageWarningResolution `json:"resolution,omitempty"`

	// Severity Severity level of this warning
	Severity *MessageWarningSeverity `json:"severity,omitempty"`

	// Type Message type discriminator
	Type MessageWarningType `json:"type"`
}

// MessageWarningCode Warning code indicating the type of warning
type MessageWarningCode string

// MessageWarningContentType Format of the warning message content. When set to 'markdown', content MUST conform to CommonMark (https://spec.commonmark.org/0.31.2/). Raw HTML elements MUST NOT be included. When set to 'plain', content is plain text with no formatting.
type MessageWarningContentType string

// MessageWarningResolution Who resolves this message. 'recoverable': agent can fix via API. 'requires_buyer_input': buyer must provide info. 'requires_buyer_review': buyer must authorize.
type MessageWarningResolution string

// MessageWarningSeverity Severity level of this warning
type MessageWarningSeverity string

// MessageWarningType Message type discriminator
type MessageWarningType string

// TaxBreakdownItem Breakdown of tax amounts by type, jurisdiction, or rate
type TaxBreakdownItem struct {
	// Amount Tax amount in minor currency units (e.g. 100 cents for $1.00 or 100 for ¥100)
	Amount int `json:"amount"`

	// Jurisdiction Tax jurisdiction name (e.g., 'California State Tax', 'City of San Francisco')
	Jurisdiction string `json:"jurisdiction"`

	// Rate Tax rate as a decimal (e.g., 0.0875 for 8.75%)
	Rate float32 `json:"rate"`
}

// TaxExemption Tax exemption information including exemption type and applicable regions
type TaxExemption struct {
	// CertificateId Unique identifier for the tax exemption certificate
	CertificateId string `json:"certificate_id"`

	// CertificateType Type of tax exemption certificate
	CertificateType TaxExemptionCertificateType `json:"certificate_type"`

	// ExemptRegions List of regions where the exemption applies (e.g., state codes)
	ExemptRegions *[]string `json:"exempt_regions,omitempty"`

	// ExpiresAt RFC 3339 timestamp when the exemption certificate expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
}

// TaxExemptionCertificateType Type of tax exemption certificate
type TaxExemptionCertificateType string

// Total Total amounts for the checkout including subtotal, discounts, tax, shipping, and final total
type Total struct {
	// Amount Amount in minor currency units (e.g. 100 cents for $1.00 or 100 for ¥100)
	Amount int `json:"amount"`

	// Breakdown Detailed breakdown for tax totals
	Breakdown *[]TaxBreakdownItem `json:"breakdown,omitempty"`

	// Description Additional descriptive text for this total
	Description *string `json:"description,omitempty"`

	// DisplayText Localized display text for this total
	DisplayText string `json:"display_text"`

	// PresentmentAmount Amount in presentment currency minor units if different from settlement currency
	PresentmentAmount *int `json:"presentment_amount,omitempty"`

	// Type Type of total line item
	Type TotalType `json:"type"`
}

// TotalType Type of total line item
type TotalType string

// VariantOption Represents a single variant option for a product (e.g., size, color, material)
type VariantOption struct {
	// Name Variant attribute name (e.g., 'Size', 'Color')
	Name string `json:"name"`

	// Value Variant attribute value (e.g., 'Large', 'Blue')
	Value string `json:"value"`
}

// WeightInfo Product weight with unit of measurement
type WeightInfo struct {
	// Unit Unit of measurement for weight
	Unit WeightInfoUnit `json:"unit"`

	// Value Numeric weight value
	Value float32 `json:"value"`
}

// WeightInfoUnit Unit of measurement for weight
type WeightInfoUnit string

// APIVersion defines model for APIVersion.
type APIVersion = string

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage = string

// Authorization defines model for Authorization.
type Authorization = string

// CartId defines model for CartId.
type CartId = string

// ContentType defines model for ContentType.
type ContentType = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// RequestId defines model for RequestId.
type RequestId = string

// BadRequest Protocol-level error returned in 4xx/5xx responses when the server cannot return a valid CheckoutSession at all (e.g. malformed request or unexpected failure). Use Error—not MessageError—when there is no valid session state to return. type semantics: invalid_request — malformed request, missing required fields, invalid JSON, or idempotency violations (codes: idempotency_key_required, idempotency_in_flight, idempotency_conflict); processing_error — unexpected server-side failure; service_unavailable — temporary unavailability.
type BadRequest = Error

// CartNotFound Protocol-level error returned in 4xx/5xx responses when the server cannot return a valid CheckoutSession at all (e.g. malformed request or unexpected failure). Use Error—not MessageError—when there is no valid session state to return. type semantics: invalid_request — malformed request, missing required fields, invalid JSON, or idempotency violations (codes: idempotency_key_required, idempotency_in_flight, idempotency_conflict); processing_error — unexpected server-side failure; service_unavailable — temporary unavailability.
type CartNotFound = Error

// Unauthorized Protocol-level error returned in 4xx/5xx responses when the server cannot return a valid CheckoutSession at all (e.g. malformed request or unexpected failure). Use Error—not MessageError—when there is no valid session state to return. type semantics: invalid_request — malformed request, missing required fields, invalid JSON, or idempotency violations (codes: idempotency_key_required, idempotency_in_flight, idempotency_conflict); processing_error — unexpected server-side failure; service_unavailable — temporary unavailability.
type Unauthorized = Error

// CreateCartParams defines parameters for CreateCart.
type CreateCartParams struct {
	// Authorization Bearer token for API authentication
	Authorization  Authorization   `json:"Authorization"`
	ContentType    ContentType     `json:"Content-Type"`
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`

	// IdempotencyKey Idempotency key. MUST be present on all POST requests. Opaque string, max 255 characters. UUID v4 recommended.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
	RequestId      *RequestId     `json:"Request-Id,omitempty"`
	APIVersion     APIVersion     `json:"API-Version"`
}

// GetCartParams defines parameters for GetCart.
type GetCartParams struct {
	// Authorization Bearer token for API authentication
	Authorization  Authorization   `json:"Authorization"`
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
	RequestId      *RequestId      `json:"Request-Id,omitempty"`
	APIVersion     APIVersion      `json:"API-Version"`
}

// UpdateCartParams defines parameters for UpdateCart.
type UpdateCartParams struct {
	// Authorization Bearer token for API authentication
	Authorization  Authorization   `json:"Authorization"`
	ContentType    ContentType     `json:"Content-Type"`
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`

	// IdempotencyKey Idempotency key. MUST be present on all POST requests. Opaque string, max 255 characters. UUID v4 recommended.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
	RequestId      *RequestId     `json:"Request-Id,omitempty"`
	APIVersion     APIVersion     `json:"API-Version"`
}

// CancelCartJSONBody defines parameters for CancelCart.
type CancelCartJSONBody = map[string]interface{}

// CancelCartParams defines parameters for CancelCart.
type CancelCartParams struct {
	// Authorization Bearer token for API authentication
	Authorization Authorization `json:"Authorization"`

	// IdempotencyKey Idempotency key. MUST be present on all POST requests. Opaque string, max 255 characters. UUID v4 recommended.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
	RequestId      *RequestId     `json:"Request-Id,omitempty"`
	APIVersion     APIVersion     `json:"API-Version"`
}

// CreateCartJSONRequestBody defines body for CreateCart for application/json ContentType.
type CreateCartJSONRequestBody = CartCreateRequest

// UpdateCartJSONRequestBody defines body for UpdateCart for application/json ContentType.
type UpdateCartJSONRequestBody = CartUpdateRequest

// CancelCartJSONRequestBody defines body for CancelCart for application/json ContentType.
type CancelCartJSONRequestBody = CancelCartJSONBody

// AsMessageInfo returns the union data inside the Cart_Messages_Item as a MessageInfo
func (t Cart_Messages_Item) AsMessageInfo() (MessageInfo, error) {
	var body MessageInfo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageInfo overwrites any union data inside the Cart_Messages_Item as the provided MessageInfo
func (t *Cart_Messages_Item) FromMessageInfo(v MessageInfo) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageInfo performs a merge with any union data inside the Cart_Messages_Item, using the provided MessageInfo
func (t *Cart_Messages_Item) MergeMessageInfo(v MessageInfo) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageWarning returns the union data inside the Cart_Messages_Item as a MessageWarning
func (t Cart_Messages_Item) AsMessageWarning() (MessageWarning, error) {
	var body MessageWarning
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageWarning overwrites any union data inside the Cart_Messages_Item as the provided MessageWarning
func (t *Cart_Messages_Item) FromMessageWarning(v MessageWarning) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageWarning performs a merge with any union data inside the Cart_Messages_Item, using the provided MessageWarning
func (t *Cart_Messages_Item) MergeMessageWarning(v MessageWarning) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageError returns the union data inside the Cart_Messages_Item as a MessageError
func (t Cart_Messages_Item) AsMessageError() (MessageError, error) {
	var body MessageError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageError overwrites any union data inside the Cart_Messages_Item as the provided MessageError
func (t *Cart_Messages_Item) FromMessageError(v MessageError) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageError performs a merge with any union data inside the Cart_Messages_Item, using the provided MessageError
func (t *Cart_Messages_Item) MergeMessageError(v MessageError) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Cart_Messages_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Cart_Messages_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
