// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package extension

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "regexp"
import "strings"

// Registry of core ACP extensions.
type CoreExtensions struct {
	// Discount corresponds to the JSON schema field "discount".
	Discount *CoreExtensionsDiscount `json:"discount,omitempty,omitzero" yaml:"discount,omitempty" mapstructure:"discount,omitempty"`
}

// Full metadata about an extension for documentation and discovery.
type CoreExtensionsDiscount struct {
	// Extensions that this extension depends on.
	DependsOn []ExtensionIdentifier `json:"depends_on,omitempty,omitzero" yaml:"depends_on,omitempty" mapstructure:"depends_on,omitempty"`

	// Brief description of what the extension provides.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// JSONPath expressions identifying the schema fields added by this extension.
	Extends []ExtendsTarget `json:"extends,omitempty,omitzero" yaml:"extends,omitempty" mapstructure:"extends,omitempty"`

	// Unique identifier for the extension.
	Id ExtensionIdentifier `json:"id" yaml:"id" mapstructure:"id"`

	// Human-readable name for the extension.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// URL to the extension JSON Schema.
	Schema *string `json:"schema,omitempty,omitzero" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// URL to the extension specification document.
	Spec *string `json:"spec,omitempty,omitzero" yaml:"spec,omitempty" mapstructure:"spec,omitempty"`

	// Lifecycle status of the extension.
	Status *ExtensionMetadataStatus `json:"status,omitempty,omitzero" yaml:"status,omitempty" mapstructure:"status,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CoreExtensionsDiscount) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in CoreExtensionsDiscount: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in CoreExtensionsDiscount: required")
	}
	type Plain CoreExtensionsDiscount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Description != nil && *plain.Description != "Discount code support with rich applied discounts, allocation details, and rejection messaging." {
		return fmt.Errorf("field %s: must be equal to %s", "description", "Discount code support with rich applied discounts, allocation details, and rejection messaging.")
	}
	if plain.Name != "Discount Extension" {
		return fmt.Errorf("field %s: must be equal to %s", "name", "Discount Extension")
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CoreExtensionsDiscount(plain)
	return nil
}

// JSONPath expression identifying the schema field added by this extension.
// Format: $.<SchemaName>.<fieldName> (e.g., $.CheckoutSession.discounts).
type ExtendsTarget string

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExtendsTarget) UnmarshalJSON(value []byte) error {
	type Plain ExtendsTarget
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^\$\.[A-Za-z][A-Za-z0-9]*(\.[A-Za-z][A-Za-z0-9_]*)*$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^\$\.[A-Za-z][A-Za-z0-9]*(\.[A-Za-z][A-Za-z0-9_]*)*$`)
	}
	*j = ExtendsTarget(plain)
	return nil
}

// Extension declaration in capabilities.extensions (response). Describes an active
// extension and which schema fields it adds.
type ExtensionDeclaration struct {
	// JSONPath expressions identifying the schema fields added by this extension
	// (e.g., $.CheckoutSession.discounts).
	Extends []ExtendsTarget `json:"extends,omitempty,omitzero" yaml:"extends,omitempty" mapstructure:"extends,omitempty"`

	// Unique identifier for the extension.
	Name ExtensionIdentifier `json:"name" yaml:"name" mapstructure:"name"`

	// URL to the extension's JSON Schema definition.
	Schema *string `json:"schema,omitempty,omitzero" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// URL to the extension's specification document.
	Spec *string `json:"spec,omitempty,omitzero" yaml:"spec,omitempty" mapstructure:"spec,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExtensionDeclaration) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ExtensionDeclaration: required")
	}
	type Plain ExtensionDeclaration
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ExtensionDeclaration(plain)
	return nil
}

// Extension identifier. Core extensions use simple names (e.g., 'discount').
// Third-party extensions use reverse-domain naming (e.g., 'com.example.custom').
// May include optional version suffix (e.g., 'discount@2026-01-27').
type ExtensionIdentifier string

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExtensionIdentifier) UnmarshalJSON(value []byte) error {
	type Plain ExtensionIdentifier
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z][a-z0-9_-]*(@\d{4}-\d{2}-\d{2})?$|^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9_-]*)+(@\d{4}-\d{2}-\d{2})?$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[a-z][a-z0-9_-]*(@\d{4}-\d{2}-\d{2})?$|^[a-z][a-z0-9]*(?:\.[a-z][a-z0-9_-]*)+(@\d{4}-\d{2}-\d{2})?$`)
	}
	*j = ExtensionIdentifier(plain)
	return nil
}

// Full metadata about an extension for documentation and discovery.
type ExtensionMetadata struct {
	// Extensions that this extension depends on.
	DependsOn []ExtensionIdentifier `json:"depends_on,omitempty,omitzero" yaml:"depends_on,omitempty" mapstructure:"depends_on,omitempty"`

	// Brief description of what the extension provides.
	Description *string `json:"description,omitempty,omitzero" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// JSONPath expressions identifying the schema fields added by this extension.
	Extends []ExtendsTarget `json:"extends,omitempty,omitzero" yaml:"extends,omitempty" mapstructure:"extends,omitempty"`

	// Unique identifier for the extension.
	Id ExtensionIdentifier `json:"id" yaml:"id" mapstructure:"id"`

	// Human-readable name for the extension.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// URL to the extension JSON Schema.
	Schema *string `json:"schema,omitempty,omitzero" yaml:"schema,omitempty" mapstructure:"schema,omitempty"`

	// URL to the extension specification document.
	Spec *string `json:"spec,omitempty,omitzero" yaml:"spec,omitempty" mapstructure:"spec,omitempty"`

	// Lifecycle status of the extension.
	Status *ExtensionMetadataStatus `json:"status,omitempty,omitzero" yaml:"status,omitempty" mapstructure:"status,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ExtensionMetadataStatus string

const ExtensionMetadataStatusDeprecated ExtensionMetadataStatus = "deprecated"
const ExtensionMetadataStatusDraft ExtensionMetadataStatus = "draft"
const ExtensionMetadataStatusExperimental ExtensionMetadataStatus = "experimental"
const ExtensionMetadataStatusRetired ExtensionMetadataStatus = "retired"
const ExtensionMetadataStatusStable ExtensionMetadataStatus = "stable"

var enumValues_ExtensionMetadataStatus = []interface{}{
	"draft",
	"experimental",
	"stable",
	"deprecated",
	"retired",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExtensionMetadataStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ExtensionMetadataStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ExtensionMetadataStatus, v)
	}
	*j = ExtensionMetadataStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ExtensionMetadata) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ExtensionMetadata: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in ExtensionMetadata: required")
	}
	type Plain ExtensionMetadata
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = ExtensionMetadata(plain)
	return nil
}

// Extensions the agent understands. Sent in request capabilities.extensions.
type RequestExtensions []ExtensionIdentifier

// Active extensions for this session. Returned in response
// capabilities.extensions.
type ResponseExtensions []ExtensionDeclaration
