// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mock_test.go -package=agentic_checkout_test
//

// Package agentic_checkout_test is a generated GoMock package.
package agentic_checkout_test

import (
	context "context"
	reflect "reflect"

	agentic_checkout "github.com/sumup/acp/agentic_checkout"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckoutProvider is a mock of CheckoutProvider interface.
type MockCheckoutProvider struct {
	ctrl     *gomock.Controller
	recorder *MockCheckoutProviderMockRecorder
	isgomock struct{}
}

// MockCheckoutProviderMockRecorder is the mock recorder for MockCheckoutProvider.
type MockCheckoutProviderMockRecorder struct {
	mock *MockCheckoutProvider
}

// NewMockCheckoutProvider creates a new mock instance.
func NewMockCheckoutProvider(ctrl *gomock.Controller) *MockCheckoutProvider {
	mock := &MockCheckoutProvider{ctrl: ctrl}
	mock.recorder = &MockCheckoutProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckoutProvider) EXPECT() *MockCheckoutProviderMockRecorder {
	return m.recorder
}

// CancelSession mocks base method.
func (m *MockCheckoutProvider) CancelSession(ctx context.Context, id string, req *agentic_checkout.CancelSessionRequest) (*agentic_checkout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSession", ctx, id, req)
	ret0, _ := ret[0].(*agentic_checkout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelSession indicates an expected call of CancelSession.
func (mr *MockCheckoutProviderMockRecorder) CancelSession(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSession", reflect.TypeOf((*MockCheckoutProvider)(nil).CancelSession), ctx, id, req)
}

// CompleteSession mocks base method.
func (m *MockCheckoutProvider) CompleteSession(ctx context.Context, id string, req agentic_checkout.CheckoutSessionCompleteRequest) (agentic_checkout.CheckoutSessionWithOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSession", ctx, id, req)
	ret0, _ := ret[0].(agentic_checkout.CheckoutSessionWithOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteSession indicates an expected call of CompleteSession.
func (mr *MockCheckoutProviderMockRecorder) CompleteSession(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSession", reflect.TypeOf((*MockCheckoutProvider)(nil).CompleteSession), ctx, id, req)
}

// CreateSession mocks base method.
func (m *MockCheckoutProvider) CreateSession(ctx context.Context, req agentic_checkout.CheckoutSessionCreateRequest) (*agentic_checkout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, req)
	ret0, _ := ret[0].(*agentic_checkout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockCheckoutProviderMockRecorder) CreateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockCheckoutProvider)(nil).CreateSession), ctx, req)
}

// GetSession mocks base method.
func (m *MockCheckoutProvider) GetSession(ctx context.Context, id string) (*agentic_checkout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(*agentic_checkout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockCheckoutProviderMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockCheckoutProvider)(nil).GetSession), ctx, id)
}

// UpdateSession mocks base method.
func (m *MockCheckoutProvider) UpdateSession(ctx context.Context, id string, req agentic_checkout.CheckoutSessionUpdateRequest) (*agentic_checkout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, id, req)
	ret0, _ := ret[0].(*agentic_checkout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockCheckoutProviderMockRecorder) UpdateSession(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockCheckoutProvider)(nil).UpdateSession), ctx, id, req)
}
