// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mock_test.go -package=acpcheckout_test
//

// Package acpcheckout_test is a generated GoMock package.
package acpcheckout_test

import (
	context "context"
	reflect "reflect"

	acpcheckout "github.com/sumup/acp/acpcheckout"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// CancelSession mocks base method.
func (m *MockProvider) CancelSession(ctx context.Context, id string, req *acpcheckout.CancelSessionRequest) (*acpcheckout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelSession", ctx, id, req)
	ret0, _ := ret[0].(*acpcheckout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelSession indicates an expected call of CancelSession.
func (mr *MockProviderMockRecorder) CancelSession(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSession", reflect.TypeOf((*MockProvider)(nil).CancelSession), ctx, id, req)
}

// CompleteSession mocks base method.
func (m *MockProvider) CompleteSession(ctx context.Context, id string, req acpcheckout.CheckoutSessionCompleteRequest) (acpcheckout.CheckoutSessionWithOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteSession", ctx, id, req)
	ret0, _ := ret[0].(acpcheckout.CheckoutSessionWithOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteSession indicates an expected call of CompleteSession.
func (mr *MockProviderMockRecorder) CompleteSession(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteSession", reflect.TypeOf((*MockProvider)(nil).CompleteSession), ctx, id, req)
}

// CreateSession mocks base method.
func (m *MockProvider) CreateSession(ctx context.Context, req acpcheckout.CheckoutSessionCreateRequest) (*acpcheckout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, req)
	ret0, _ := ret[0].(*acpcheckout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockProviderMockRecorder) CreateSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockProvider)(nil).CreateSession), ctx, req)
}

// GetSession mocks base method.
func (m *MockProvider) GetSession(ctx context.Context, id string) (*acpcheckout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(*acpcheckout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockProviderMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockProvider)(nil).GetSession), ctx, id)
}

// UpdateSession mocks base method.
func (m *MockProvider) UpdateSession(ctx context.Context, id string, req acpcheckout.CheckoutSessionUpdateRequest) (*acpcheckout.CheckoutSessionBase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", ctx, id, req)
	ret0, _ := ret[0].(*acpcheckout.CheckoutSessionBase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockProviderMockRecorder) UpdateSession(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockProvider)(nil).UpdateSession), ctx, id, req)
}
