// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mock_test.go -package=delegate_payment_test
//

// Package delegate_payment_test is a generated GoMock package.
package delegate_payment_test

import (
	context "context"
	reflect "reflect"

	delegate_payment "github.com/sumup/acp/delegate_payment"
	gomock "go.uber.org/mock/gomock"
)

// MockDelegatedPaymentProvider is a mock of DelegatedPaymentProvider interface.
type MockDelegatedPaymentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDelegatedPaymentProviderMockRecorder
	isgomock struct{}
}

// MockDelegatedPaymentProviderMockRecorder is the mock recorder for MockDelegatedPaymentProvider.
type MockDelegatedPaymentProviderMockRecorder struct {
	mock *MockDelegatedPaymentProvider
}

// NewMockDelegatedPaymentProvider creates a new mock instance.
func NewMockDelegatedPaymentProvider(ctrl *gomock.Controller) *MockDelegatedPaymentProvider {
	mock := &MockDelegatedPaymentProvider{ctrl: ctrl}
	mock.recorder = &MockDelegatedPaymentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDelegatedPaymentProvider) EXPECT() *MockDelegatedPaymentProviderMockRecorder {
	return m.recorder
}

// DelegatePayment mocks base method.
func (m *MockDelegatedPaymentProvider) DelegatePayment(ctx context.Context, req delegate_payment.DelegatePaymentRequest) (*delegate_payment.DelegatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegatePayment", ctx, req)
	ret0, _ := ret[0].(*delegate_payment.DelegatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DelegatePayment indicates an expected call of DelegatePayment.
func (mr *MockDelegatedPaymentProviderMockRecorder) DelegatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegatePayment", reflect.TypeOf((*MockDelegatedPaymentProvider)(nil).DelegatePayment), ctx, req)
}
