// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package discount

import "encoding/json"
import "fmt"
import "reflect"
import "regexp"
import "time"

// Breakdown of how a discount amount was allocated to a specific target.
type Allocation struct {
	// Amount allocated to this target in minor (cents) currency units.
	Amount int `json:"amount" yaml:"amount" mapstructure:"amount"`

	// JSONPath to the allocation target (e.g., '$.line_items[0]',
	// '$.totals.shipping').
	Path string `json:"path" yaml:"path" mapstructure:"path"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Allocation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in Allocation: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in Allocation: required")
	}
	type Plain Allocation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Amount {
		return fmt.Errorf("field %s: must be >= %v", "amount", 0)
	}
	*j = Allocation(plain)
	return nil
}

// A discount that was successfully applied to the checkout session.
type AppliedDiscount struct {
	// Breakdown of where this discount was allocated. Sum of allocation amounts
	// equals total amount.
	Allocations []Allocation `json:"allocations,omitempty" yaml:"allocations,omitempty" mapstructure:"allocations,omitempty"`

	// Total discount amount in minor (cents) currency units.
	Amount int `json:"amount" yaml:"amount" mapstructure:"amount"`

	// True if applied automatically by merchant rules (no code required).
	Automatic bool `json:"automatic,omitempty" yaml:"automatic,omitempty" mapstructure:"automatic,omitempty"`

	// The discount code entered by the user. Omitted for automatic discounts.
	Code *string `json:"code,omitempty" yaml:"code,omitempty" mapstructure:"code,omitempty"`

	// Details about the underlying coupon/promotion.
	Coupon Coupon `json:"coupon" yaml:"coupon" mapstructure:"coupon"`

	// RFC 3339 timestamp when the discount expires.
	End *time.Time `json:"end,omitempty" yaml:"end,omitempty" mapstructure:"end,omitempty"`

	// Unique identifier for this applied discount instance.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Allocation method. 'each' = applied independently per item (allocations
	// typically included). 'across' = applied to order total (allocations typically
	// omitted).
	Method *AppliedDiscountMethod `json:"method,omitempty" yaml:"method,omitempty" mapstructure:"method,omitempty"`

	// Stacking order for discount calculation. Lower numbers applied first (1 =
	// first).
	Priority *int `json:"priority,omitempty" yaml:"priority,omitempty" mapstructure:"priority,omitempty"`

	// RFC 3339 timestamp when the discount became active.
	Start *time.Time `json:"start,omitempty" yaml:"start,omitempty" mapstructure:"start,omitempty"`
}

type AppliedDiscountMethod string

const AppliedDiscountMethodAcross AppliedDiscountMethod = "across"
const AppliedDiscountMethodEach AppliedDiscountMethod = "each"

var enumValues_AppliedDiscountMethod = []interface{}{
	"each",
	"across",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AppliedDiscountMethod) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AppliedDiscountMethod {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AppliedDiscountMethod, v)
	}
	*j = AppliedDiscountMethod(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AppliedDiscount) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["amount"]; raw != nil && !ok {
		return fmt.Errorf("field amount in AppliedDiscount: required")
	}
	if _, ok := raw["coupon"]; raw != nil && !ok {
		return fmt.Errorf("field coupon in AppliedDiscount: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in AppliedDiscount: required")
	}
	type Plain AppliedDiscount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 > plain.Amount {
		return fmt.Errorf("field %s: must be >= %v", "amount", 0)
	}
	if v, ok := raw["automatic"]; !ok || v == nil {
		plain.Automatic = false
	}
	if plain.Priority != nil && 1 > *plain.Priority {
		return fmt.Errorf("field %s: must be >= %v", "priority", 1)
	}
	*j = AppliedDiscount(plain)
	return nil
}

// Checkout session create request extended with discount codes.
type CheckoutCreateRequestWithDiscount interface{}

// Checkout session update request extended with discount codes.
type CheckoutUpdateRequestWithDiscount interface{}

// Checkout session extended with discount capability.
type CheckoutWithDiscount interface{}

// Coupon details describing the discount terms.
type Coupon struct {
	// Fixed discount amount in minor currency units. Mutually exclusive with
	// percent_off.
	AmountOff *int `json:"amount_off,omitempty" yaml:"amount_off,omitempty" mapstructure:"amount_off,omitempty"`

	// ISO 4217 currency code for amount_off. Required if amount_off is set.
	Currency *string `json:"currency,omitempty" yaml:"currency,omitempty" mapstructure:"currency,omitempty"`

	// How long the discount applies. 'once' = single use, 'repeating' = multiple
	// billing periods, 'forever' = indefinitely.
	Duration *CouponDuration `json:"duration,omitempty" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// Number of months the coupon applies if duration is 'repeating'.
	DurationInMonths *int `json:"duration_in_months,omitempty" yaml:"duration_in_months,omitempty" mapstructure:"duration_in_months,omitempty"`

	// Unique identifier for the coupon.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Maximum number of times this coupon can be redeemed across all customers.
	MaxRedemptions *int `json:"max_redemptions,omitempty" yaml:"max_redemptions,omitempty" mapstructure:"max_redemptions,omitempty"`

	// Arbitrary key-value metadata attached to the coupon.
	Metadata CouponMetadata `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Human-readable coupon name (e.g., 'Summer Sale 20% Off').
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Percentage discount (0-100). Mutually exclusive with amount_off.
	PercentOff *float64 `json:"percent_off,omitempty" yaml:"percent_off,omitempty" mapstructure:"percent_off,omitempty"`

	// Number of times this coupon has been redeemed.
	TimesRedeemed *int `json:"times_redeemed,omitempty" yaml:"times_redeemed,omitempty" mapstructure:"times_redeemed,omitempty"`
}

type CouponDuration string

const CouponDurationForever CouponDuration = "forever"
const CouponDurationOnce CouponDuration = "once"
const CouponDurationRepeating CouponDuration = "repeating"

var enumValues_CouponDuration = []interface{}{
	"once",
	"repeating",
	"forever",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CouponDuration) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CouponDuration {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CouponDuration, v)
	}
	*j = CouponDuration(v)
	return nil
}

// Arbitrary key-value metadata attached to the coupon.
type CouponMetadata map[string]string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Coupon) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Coupon: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Coupon: required")
	}
	type Plain Coupon
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.AmountOff != nil && 0 > *plain.AmountOff {
		return fmt.Errorf("field %s: must be >= %v", "amount_off", 0)
	}
	if plain.Currency != nil {
		if matched, _ := regexp.MatchString(`^[a-z]{3}$`, string(*plain.Currency)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "Currency", `^[a-z]{3}$`)
		}
	}
	if plain.DurationInMonths != nil && 1 > *plain.DurationInMonths {
		return fmt.Errorf("field %s: must be >= %v", "duration_in_months", 1)
	}
	if plain.MaxRedemptions != nil && 1 > *plain.MaxRedemptions {
		return fmt.Errorf("field %s: must be >= %v", "max_redemptions", 1)
	}
	if plain.PercentOff != nil && 100 < *plain.PercentOff {
		return fmt.Errorf("field %s: must be <= %v", "percent_off", 100)
	}
	if plain.PercentOff != nil && 0 > *plain.PercentOff {
		return fmt.Errorf("field %s: must be >= %v", "percent_off", 0)
	}
	if plain.TimesRedeemed != nil && 0 > *plain.TimesRedeemed {
		return fmt.Errorf("field %s: must be >= %v", "times_redeemed", 0)
	}
	*j = Coupon(plain)
	return nil
}

type DiscountErrorCodes string

const DiscountErrorCodesDiscountCodeAlreadyApplied DiscountErrorCodes = "discount_code_already_applied"
const DiscountErrorCodesDiscountCodeCombinationDisallowed DiscountErrorCodes = "discount_code_combination_disallowed"
const DiscountErrorCodesDiscountCodeExpired DiscountErrorCodes = "discount_code_expired"
const DiscountErrorCodesDiscountCodeInvalid DiscountErrorCodes = "discount_code_invalid"
const DiscountErrorCodesDiscountCodeMinimumNotMet DiscountErrorCodes = "discount_code_minimum_not_met"
const DiscountErrorCodesDiscountCodeUsageLimitReached DiscountErrorCodes = "discount_code_usage_limit_reached"
const DiscountErrorCodesDiscountCodeUserIneligible DiscountErrorCodes = "discount_code_user_ineligible"
const DiscountErrorCodesDiscountCodeUserNotLoggedIn DiscountErrorCodes = "discount_code_user_not_logged_in"

var enumValues_DiscountErrorCodes = []interface{}{
	"discount_code_expired",
	"discount_code_invalid",
	"discount_code_already_applied",
	"discount_code_combination_disallowed",
	"discount_code_minimum_not_met",
	"discount_code_user_not_logged_in",
	"discount_code_user_ineligible",
	"discount_code_usage_limit_reached",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DiscountErrorCodes) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DiscountErrorCodes {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_DiscountErrorCodes, v)
	}
	*j = DiscountErrorCodes(v)
	return nil
}

// Discount codes input for checkout create/update requests.
type DiscountsRequest struct {
	// Discount codes to apply. Case-insensitive. Replaces previously submitted codes.
	// Send empty array to clear.
	Codes []string `json:"codes,omitempty" yaml:"codes,omitempty" mapstructure:"codes,omitempty"`
}

// Discount codes input, applied discounts, and rejected codes in checkout
// responses.
type DiscountsResponse struct {
	// Discounts successfully applied (code-based and automatic).
	Applied []AppliedDiscount `json:"applied,omitempty" yaml:"applied,omitempty" mapstructure:"applied,omitempty"`

	// Echo of submitted discount codes.
	Codes []string `json:"codes,omitempty" yaml:"codes,omitempty" mapstructure:"codes,omitempty"`

	// Discount codes that could not be applied, with reasons.
	Rejected []RejectedDiscount `json:"rejected,omitempty" yaml:"rejected,omitempty" mapstructure:"rejected,omitempty"`
}

// A discount code that could not be applied, with the reason.
type RejectedDiscount struct {
	// The discount code that was rejected.
	Code string `json:"code" yaml:"code" mapstructure:"code"`

	// Human-readable explanation of why the code was rejected.
	Message *string `json:"message,omitempty" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Error code indicating why the discount was rejected.
	Reason DiscountErrorCodes `json:"reason" yaml:"reason" mapstructure:"reason"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RejectedDiscount) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["code"]; raw != nil && !ok {
		return fmt.Errorf("field code in RejectedDiscount: required")
	}
	if _, ok := raw["reason"]; raw != nil && !ok {
		return fmt.Errorf("field reason in RejectedDiscount: required")
	}
	type Plain RejectedDiscount
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RejectedDiscount(plain)
	return nil
}
