// Package acppayment provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package acppayment

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AllowanceReason.
const (
	OneTime AllowanceReason = "one_time"
)

// Defines values for ErrorCode.
const (
	DuplicateRequest    ErrorCode = "duplicate_request"
	IdempotencyConflict ErrorCode = "idempotency_conflict"
	InvalidCard         ErrorCode = "invalid_card"
	TooManyRequests     ErrorCode = "too_many_requests"
)

// Defines values for ErrorType.
const (
	InvalidRequest     ErrorType = "invalid_request"
	ProcessingError    ErrorType = "processing_error"
	RateLimitExceeded  ErrorType = "rate_limit_exceeded"
	ServiceUnavailable ErrorType = "service_unavailable"
)

// Defines values for PaymentMethodCardCardNumberType.
const (
	Fpan         PaymentMethodCardCardNumberType = "fpan"
	NetworkToken PaymentMethodCardCardNumberType = "network_token"
)

// Defines values for PaymentMethodCardChecksPerformed.
const (
	Ani   PaymentMethodCardChecksPerformed = "ani"
	Auth0 PaymentMethodCardChecksPerformed = "auth0"
	Avs   PaymentMethodCardChecksPerformed = "avs"
	Cvv   PaymentMethodCardChecksPerformed = "cvv"
)

// Defines values for PaymentMethodCardDisplayCardFundingType.
const (
	Credit  PaymentMethodCardDisplayCardFundingType = "credit"
	Debit   PaymentMethodCardDisplayCardFundingType = "debit"
	Prepaid PaymentMethodCardDisplayCardFundingType = "prepaid"
)

// Defines values for PaymentMethodCardType.
const (
	Card PaymentMethodCardType = "card"
)

// Defines values for RiskSignalAction.
const (
	Authorized   RiskSignalAction = "authorized"
	Blocked      RiskSignalAction = "blocked"
	ManualReview RiskSignalAction = "manual_review"
)

// Defines values for RiskSignalType.
const (
	CardTesting RiskSignalType = "card_testing"
)

// Address defines model for Address.
type Address struct {
	// City City or locality
	City string `json:"city"`

	// Country ISO-3166-1 alpha-2 country code
	Country string `json:"country"`

	// LineOne Street address line 1 (e.g., street and number)
	LineOne string `json:"line_one"`

	// LineTwo Street address line 2 (e.g., apartment, suite, unit)
	LineTwo *string `json:"line_two,omitempty"`

	// Name Full name of the person at this address
	Name string `json:"name"`

	// PostalCode ZIP or postal code
	PostalCode string `json:"postal_code"`

	// State State, province, or region
	State string `json:"state"`
}

// Allowance defines model for Allowance.
type Allowance struct {
	// CheckoutSessionId Identifier of the checkout session this payment is for
	CheckoutSessionId string `json:"checkout_session_id"`

	// Currency ISO-4217 three-letter lowercase currency code (e.g., usd)
	Currency string `json:"currency"`

	// ExpiresAt ISO 8601 timestamp when this allowance expires
	ExpiresAt time.Time `json:"expires_at"`

	// MaxAmount Maximum charge amount in minor units (e.g. 100 cents for $1.00 or 100 for ¥100)
	MaxAmount int `json:"max_amount"`

	// MerchantId Unique identifier for the merchant authorized to use this token
	MerchantId string `json:"merchant_id"`

	// Reason Usage pattern for this allowance; currently only one_time is supported
	Reason AllowanceReason `json:"reason"`
}

// AllowanceReason Usage pattern for this allowance; currently only one_time is supported
type AllowanceReason string

// DelegatePaymentRequest defines model for DelegatePaymentRequest.
type DelegatePaymentRequest struct {
	Allowance      Allowance `json:"allowance"`
	BillingAddress *Address  `json:"billing_address,omitempty"`

	// Metadata Additional metadata for the request
	Metadata      map[string]string `json:"metadata"`
	PaymentMethod PaymentMethodCard `json:"payment_method"`

	// RiskSignals List of risk assessment signals from fraud detection
	RiskSignals []RiskSignal `json:"risk_signals"`
}

// DelegatePaymentResponse defines model for DelegatePaymentResponse.
type DelegatePaymentResponse struct {
	// Created ISO 8601 timestamp when the token was created
	Created time.Time `json:"created"`

	// Id Unique vault token identifier (vt_...)
	Id string `json:"id"`

	// Metadata Metadata echoed from the request plus system-added fields
	Metadata map[string]string `json:"metadata"`
}

// Error defines model for Error.
type Error struct {
	// Code Specific error code for programmatic handling
	Code ErrorCode `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`

	// Param JSONPath of offending field
	Param *string `json:"param,omitempty"`

	// Type High-level error category
	Type ErrorType `json:"type"`
}

// ErrorCode Specific error code for programmatic handling
type ErrorCode string

// ErrorType High-level error category
type ErrorType string

// PaymentMethodCard defines model for PaymentMethodCard.
type PaymentMethodCard struct {
	// CardNumberType Whether the number is a raw card number (fpan) or a network token
	CardNumberType PaymentMethodCardCardNumberType `json:"card_number_type"`

	// ChecksPerformed List of verification checks performed on the card
	ChecksPerformed *[]PaymentMethodCardChecksPerformed `json:"checks_performed,omitempty"`

	// Cryptogram Dynamic cryptogram for tokenized card transactions
	Cryptogram *string `json:"cryptogram,omitempty"`

	// Cvc Card verification code (3 or 4 digits)
	Cvc *string `json:"cvc,omitempty"`

	// DisplayBrand Card brand for display purposes (e.g., visa, mastercard)
	DisplayBrand *string `json:"display_brand,omitempty"`

	// DisplayCardFundingType Card funding type for display purposes
	DisplayCardFundingType PaymentMethodCardDisplayCardFundingType `json:"display_card_funding_type"`

	// DisplayLast4 Last 4 digits of card number for display purposes
	DisplayLast4 *string `json:"display_last4,omitempty"`

	// DisplayWalletType Digital wallet provider if card is from a wallet (e.g., Apple Pay, Google Pay)
	DisplayWalletType *string `json:"display_wallet_type,omitempty"`

	// EciValue Electronic Commerce Indicator for 3DS authentication status
	EciValue *string `json:"eci_value,omitempty"`

	// ExpMonth Two-digit expiration month (01-12)
	ExpMonth *string `json:"exp_month,omitempty"`

	// ExpYear Four-digit expiration year (e.g., 2026)
	ExpYear *string `json:"exp_year,omitempty"`

	// Iin Issuer Identification Number (first 6 digits of card)
	Iin *string `json:"iin,omitempty"`

	// Metadata Additional metadata about the payment method
	Metadata map[string]string `json:"metadata"`

	// Name Cardholder name as it appears on the card
	Name *string `json:"name,omitempty"`

	// Number network token or fallback fpan value
	Number string `json:"number"`

	// Type Payment method type, always 'card'
	Type PaymentMethodCardType `json:"type"`

	// Virtual Whether this is a virtual card number
	Virtual *bool `json:"virtual,omitempty"`
}

// PaymentMethodCardCardNumberType Whether the number is a raw card number (fpan) or a network token
type PaymentMethodCardCardNumberType string

// PaymentMethodCardChecksPerformed defines model for PaymentMethodCard.ChecksPerformed.
type PaymentMethodCardChecksPerformed string

// PaymentMethodCardDisplayCardFundingType Card funding type for display purposes
type PaymentMethodCardDisplayCardFundingType string

// PaymentMethodCardType Payment method type, always 'card'
type PaymentMethodCardType string

// RiskSignal defines model for RiskSignal.
type RiskSignal struct {
	// Action Recommended action based on risk assessment
	Action RiskSignalAction `json:"action"`

	// Score Risk score indicating severity level
	Score int `json:"score"`

	// Type Type of risk signal detected
	Type RiskSignalType `json:"type"`
}

// RiskSignalAction Recommended action based on risk assessment
type RiskSignalAction string

// RiskSignalType Type of risk signal detected
type RiskSignalType string

// APIVersion defines model for APIVersion.
type APIVersion = string

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage = string

// Authorization defines model for Authorization.
type Authorization = string

// ContentType defines model for ContentType.
type ContentType = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// RequestId defines model for RequestId.
type RequestId = string

// Signature defines model for Signature.
type Signature = string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UserAgent defines model for UserAgent.
type UserAgent = string

// DelegatePaymentParams defines parameters for DelegatePayment.
type DelegatePaymentParams struct {
	// Authorization Bearer token for API authentication (e.g., Bearer sk_live_123)
	Authorization Authorization `json:"Authorization"`

	// ContentType Must be application/json
	ContentType ContentType `json:"Content-Type"`

	// AcceptLanguage Preferred language for response messages (e.g., en-US)
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`

	// UserAgent Client application identifier
	UserAgent *UserAgent `json:"User-Agent,omitempty"`

	// IdempotencyKey Unique key to safely retry requests without duplicate token creation
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`

	// RequestId Unique identifier for request tracking and debugging
	RequestId *RequestId `json:"Request-Id,omitempty"`

	// Signature Detached JSON signature for request verification
	Signature *Signature `json:"Signature,omitempty"`

	// Timestamp ISO 8601 timestamp for request timing validation
	Timestamp *Timestamp `json:"Timestamp,omitempty"`

	// APIVersion API version date in format YYYY-MM-DD (e.g., 2026-01-30)
	APIVersion APIVersion `json:"API-Version"`
}

// DelegatePaymentJSONRequestBody defines body for DelegatePayment for application/json ContentType.
type DelegatePaymentJSONRequestBody = DelegatePaymentRequest
