// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mock_test.go -package=acppayment_test
//

// Package acppayment_test is a generated GoMock package.
package acppayment_test

import (
	context "context"
	reflect "reflect"

	acppayment "github.com/sumup/acp/acppayment"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// DelegatePayment mocks base method.
func (m *MockProvider) DelegatePayment(ctx context.Context, req acppayment.DelegatePaymentRequest) (*acppayment.DelegatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegatePayment", ctx, req)
	ret0, _ := ret[0].(*acppayment.DelegatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DelegatePayment indicates an expected call of DelegatePayment.
func (mr *MockProviderMockRecorder) DelegatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegatePayment", reflect.TypeOf((*MockProvider)(nil).DelegatePayment), ctx, req)
}
