// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package acpfeed

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Availability Purchasability and fulfillment state for a variant.
type Availability struct {
	// Available Indicates whether the variant is currently purchasable. Use status for fulfillment context.
	Available *bool `json:"available,omitempty"`

	// Status Extensible fulfillment state for the variant. Known values include in_stock, limited_stock, backorder, preorder, out_of_stock, and discontinued.
	Status *string `json:"status,omitempty"`
}

// Barcode Machine-readable identifier attached to a variant, such as a GTIN or UPC.
type Barcode struct {
	// Type Barcode scheme or identifier type, such as GTIN, UPC, or EAN.
	Type string `json:"type"`

	// Value Raw barcode value as provided by the merchant.
	Value string `json:"value"`
}

// Category Category assignment for a product or variant within a specific taxonomy.
type Category struct {
	// Taxonomy Names the taxonomy system used for the category value, such as google_product_category, shopify, or merchant.
	Taxonomy *string `json:"taxonomy,omitempty"`

	// Value Category label or hierarchical path, for example Mens > Sweaters > Crewnecks.
	Value string `json:"value"`
}

// Condition Extensible list of applicable item conditions, such as new or secondhand.
type Condition = []string

// CreateFeedRequest Request payload used to create a feed.
type CreateFeedRequest struct {
	// TargetCountry Optional ISO 3166-1 alpha-2 country code describing the feed's target market.
	TargetCountry *string `json:"target_country,omitempty"`
}

// Description Structured long-form or rich-text description content for a product or variant.
type Description struct {
	// Html HTML-formatted description content.
	Html *string `json:"html,omitempty"`

	// Markdown Markdown-formatted description content.
	Markdown *string `json:"markdown,omitempty"`

	// Plain Plain-text description intended for clients that do not render rich formatting.
	Plain *string `json:"plain,omitempty"`
}

// Error Structured error returned when a feed request cannot be fulfilled.
type Error struct {
	// Code Machine-readable error code for programmatic handling.
	Code string `json:"code"`

	// Message Human-readable explanation of the error.
	Message string `json:"message"`

	// Param Optional request parameter or field associated with the error.
	Param *string `json:"param,omitempty"`

	// Type High-level error category.
	Type string `json:"type"`
}

// FeedMetadata Server-managed metadata describing a feed resource.
type FeedMetadata struct {
	// Id Stable identifier for the feed resource.
	Id string `json:"id"`

	// TargetCountry Optional ISO 3166-1 alpha-2 country code describing the feed's target market.
	TargetCountry *string `json:"target_country,omitempty"`

	// UpdatedAt Timestamp of the most recent update applied to this feed.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Link Merchant-provided informational or policy link associated with a seller.
type Link struct {
	// Title Human-readable label for the linked resource.
	Title *string `json:"title,omitempty"`

	// Type Extensible link type, such as privacy_policy, terms_of_service, refund_policy, shipping_policy, or faq.
	Type string `json:"type"`

	// Url Canonical URL for the linked resource.
	Url string `json:"url"`
}

// Measure Measured quantity paired with a unit for unit-price calculations.
type Measure struct {
	// Unit Unit label for the measured quantity, such as oz, ml, or kg.
	Unit string `json:"unit"`

	// Value Measured quantity for the package or item.
	Value float32 `json:"value"`
}

// Media Media asset associated with a product or variant.
type Media struct {
	// AltText Human-readable alternate text describing the asset.
	AltText *string `json:"alt_text,omitempty"`

	// Height Rendered height of the asset in pixels, when known.
	Height *int `json:"height,omitempty"`

	// Type Media kind, such as image, video, or model.
	Type string `json:"type"`

	// Url Canonical URL where the media asset can be retrieved.
	Url string `json:"url"`

	// Width Rendered width of the asset in pixels, when known.
	Width *int `json:"width,omitempty"`
}

// Price Monetary amount expressed in minor units with an associated ISO 4217 currency code.
type Price struct {
	// Amount Monetary amount expressed in ISO 4217 minor units.
	Amount int `json:"amount"`

	// Currency Three-letter ISO 4217 currency identifier.
	Currency string `json:"currency"`
}

// Product Catalog product grouping one or more purchasable variants within a feed.
type Product struct {
	// Description Structured description content for the product.
	Description *Description `json:"description,omitempty"`

	// Id Stable global identifier for this product.
	Id string `json:"id"`

	// Media Media assets associated with the product.
	Media *[]Media `json:"media,omitempty"`

	// Title Display title for the product.
	Title *string `json:"title,omitempty"`

	// Url Canonical URL for the product detail page.
	Url *string `json:"url,omitempty"`

	// Variants Purchasable variants grouped under this product.
	Variants []Variant `json:"variants"`
}

// ProductsResponse Response envelope containing the current product set for a feed.
type ProductsResponse struct {
	// Products Full list of products currently associated with the feed.
	Products []Product `json:"products"`
}

// ReferenceMeasure Reference unit used when normalizing a unit price for display.
type ReferenceMeasure struct {
	// Unit Reference unit label, such as ml, g, or oz.
	Unit string `json:"unit"`

	// Value Reference quantity used to normalize the unit price.
	Value int `json:"value"`
}

// Seller Merchant or seller identity associated with a variant offer.
type Seller struct {
	// Links Informational or policy links associated with this seller.
	Links *[]Link `json:"links,omitempty"`

	// Name Display name of the seller or merchant of record.
	Name *string `json:"name,omitempty"`
}

// UnitPrice Normalized unit price for products sold by weight, volume, or measure.
type UnitPrice struct {
	// Amount Normalized price amount expressed in ISO 4217 minor units.
	Amount int `json:"amount"`

	// Currency Three-letter ISO 4217 currency identifier.
	Currency string `json:"currency"`

	// Measure Actual packaged measure associated with the sale item.
	Measure Measure `json:"measure"`

	// Reference Reference measure used to display the normalized unit price.
	Reference ReferenceMeasure `json:"reference"`
}

// UpsertProductsRequest Request payload that partially upserts products into a feed. Products omitted from the request remain unchanged.
type UpsertProductsRequest struct {
	// Products Subset of products to create or update within the feed, matched by Product.id.
	Products []Product `json:"products"`
}

// UpsertProductsResponse Acknowledgement returned after accepting an upsert payload for a feed.
type UpsertProductsResponse struct {
	// Accepted Whether the submitted product upsert payload was accepted for processing.
	Accepted bool `json:"accepted"`

	// Id Identifier for the feed whose product upsert was processed.
	Id string `json:"id"`
}

// Variant Purchasable variant of a product within a feed.
type Variant struct {
	// Availability Purchasability and fulfillment state for the variant.
	Availability *Availability `json:"availability,omitempty"`

	// Barcodes Machine-readable identifiers associated with this variant.
	Barcodes *[]Barcode `json:"barcodes,omitempty"`

	// Categories Category assignments associated with this variant.
	Categories *[]Category `json:"categories,omitempty"`

	// Condition Extensible list of conditions applicable to this variant.
	Condition *Condition `json:"condition,omitempty"`

	// Description Structured description content for the variant.
	Description *Description `json:"description,omitempty"`

	// Id Stable global identifier for this variant.
	Id string `json:"id"`

	// ListPrice Reference or pre-discount price for the variant.
	ListPrice *Price `json:"list_price,omitempty"`

	// Marketplace Marketplace or intermediary platform through which this variant is offered, if applicable.
	Marketplace *Seller `json:"marketplace,omitempty"`

	// Media Media assets specific to this variant. The first item is the primary listing asset.
	Media *[]Media `json:"media,omitempty"`

	// Price Active selling price for the variant.
	Price *Price `json:"price,omitempty"`

	// Seller Seller or merchant of record for this variant.
	Seller *Seller `json:"seller,omitempty"`

	// Title Display title for the variant.
	Title string `json:"title"`

	// UnitPrice Normalized unit price, when applicable.
	UnitPrice *UnitPrice `json:"unit_price,omitempty"`

	// Url Canonical URL for the variant detail page.
	Url *string `json:"url,omitempty"`

	// VariantOptions Option selections that distinguish this variant, such as Color: Red or Size: Small.
	VariantOptions *[]VariantOption `json:"variant_options,omitempty"`
}

// VariantOption One selected characteristic of a variant, such as size or color.
type VariantOption struct {
	// Name Display name of the option dimension, such as Color or Size.
	Name string `json:"name"`

	// Value Selected option value for this variant.
	Value string `json:"value"`
}

// FeedId defines model for FeedId.
type FeedId = string

// CreateFeedJSONRequestBody defines body for CreateFeed for application/json ContentType.
type CreateFeedJSONRequestBody = CreateFeedRequest

// UpsertFeedProductsJSONRequestBody defines body for UpsertFeedProducts for application/json ContentType.
type UpsertFeedProductsJSONRequestBody = UpsertProductsRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CreateFeedWithBody Create a feed
	//
	// Creates a feed resource and returns server-managed metadata for the new feed.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /feeds (the `CreateFeed` operationId).
	CreateFeedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateFeed Create a feed
	//
	// Creates a feed resource and returns server-managed metadata for the new feed.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /feeds (the `CreateFeed` operationId).
	CreateFeed(ctx context.Context, body CreateFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFeed Retrieve feed metadata
	//
	// Returns server-managed metadata for the specified feed.
	//
	// Corresponds with GET /feeds/{id} (the `GetFeed` operationId).
	GetFeed(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFeedProducts Retrieve products for a feed
	//
	// Returns the full current product set for the specified feed.
	//
	// Corresponds with GET /feeds/{id}/products (the `GetFeedProducts` operationId).
	GetFeedProducts(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertFeedProductsWithBody Upsert products for a feed
	//
	// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
	UpsertFeedProductsWithBody(ctx context.Context, id FeedId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertFeedProducts Upsert products for a feed
	//
	// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
	UpsertFeedProducts(ctx context.Context, id FeedId, body UpsertFeedProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CreateFeedWithBody Create a feed
//
// Creates a feed resource and returns server-managed metadata for the new feed.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /feeds (the `CreateFeed` operationId).
func (c *Client) CreateFeedWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFeedRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateFeed Create a feed
//
// Creates a feed resource and returns server-managed metadata for the new feed.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /feeds (the `CreateFeed` operationId).
func (c *Client) CreateFeed(ctx context.Context, body CreateFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateFeedRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetFeed Retrieve feed metadata
//
// Returns server-managed metadata for the specified feed.
//
// Corresponds with GET /feeds/{id} (the `GetFeed` operationId).
func (c *Client) GetFeed(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFeedRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetFeedProducts Retrieve products for a feed
//
// Returns the full current product set for the specified feed.
//
// Corresponds with GET /feeds/{id}/products (the `GetFeedProducts` operationId).
func (c *Client) GetFeedProducts(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFeedProductsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertFeedProductsWithBody Upsert products for a feed
//
// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
func (c *Client) UpsertFeedProductsWithBody(ctx context.Context, id FeedId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertFeedProductsRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertFeedProducts Upsert products for a feed
//
// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
func (c *Client) UpsertFeedProducts(ctx context.Context, id FeedId, body UpsertFeedProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertFeedProductsRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateFeedRequest calls the generic CreateFeed builder with application/json body
func NewCreateFeedRequest(server string, body CreateFeedJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateFeedRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateFeedRequestWithBody constructs an http.Request for the CreateFeed method, with any body, and a specified content type
func NewCreateFeedRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/feeds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetFeedRequest constructs an http.Request for the GetFeed method
func NewGetFeedRequest(server string, id FeedId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/feeds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetFeedProductsRequest constructs an http.Request for the GetFeedProducts method
func NewGetFeedProductsRequest(server string, id FeedId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/feeds/%s/products", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpsertFeedProductsRequest calls the generic UpsertFeedProducts builder with application/json body
func NewUpsertFeedProductsRequest(server string, id FeedId, body UpsertFeedProductsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertFeedProductsRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpsertFeedProductsRequestWithBody constructs an http.Request for the UpsertFeedProducts method, with any body, and a specified content type
func NewUpsertFeedProductsRequestWithBody(server string, id FeedId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/feeds/%s/products", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CreateFeedWithBodyWithResponse Create a feed
	//
	// Creates a feed resource and returns server-managed metadata for the new feed.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /feeds (the `CreateFeed` operationId).
	CreateFeedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFeedResponse, error)

	// CreateFeedWithResponse Create a feed
	//
	// Creates a feed resource and returns server-managed metadata for the new feed.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /feeds (the `CreateFeed` operationId).
	CreateFeedWithResponse(ctx context.Context, body CreateFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFeedResponse, error)

	// GetFeedWithResponse Retrieve feed metadata
	//
	// Returns server-managed metadata for the specified feed.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /feeds/{id} (the `GetFeed` operationId).
	GetFeedWithResponse(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*GetFeedResponse, error)

	// GetFeedProductsWithResponse Retrieve products for a feed
	//
	// Returns the full current product set for the specified feed.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /feeds/{id}/products (the `GetFeedProducts` operationId).
	GetFeedProductsWithResponse(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*GetFeedProductsResponse, error)

	// UpsertFeedProductsWithBodyWithResponse Upsert products for a feed
	//
	// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
	UpsertFeedProductsWithBodyWithResponse(ctx context.Context, id FeedId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertFeedProductsResponse, error)

	// UpsertFeedProductsWithResponse Upsert products for a feed
	//
	// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
	UpsertFeedProductsWithResponse(ctx context.Context, id FeedId, body UpsertFeedProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertFeedProductsResponse, error)
}

type CreateFeedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *FeedMetadata
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateFeedResponse) GetJSON201() *FeedMetadata {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateFeedResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetBody returns the raw response body bytes
func (r CreateFeedResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateFeedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateFeedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateFeedResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetFeedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *FeedMetadata
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetFeedResponse) GetJSON200() *FeedMetadata {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetFeedResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetFeedResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetFeedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFeedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetFeedResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetFeedProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ProductsResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetFeedProductsResponse) GetJSON200() *ProductsResponse {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetFeedProductsResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetFeedProductsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetFeedProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFeedProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetFeedProductsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpsertFeedProductsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *UpsertProductsResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertFeedProductsResponse) GetJSON200() *UpsertProductsResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpsertFeedProductsResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpsertFeedProductsResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r UpsertFeedProductsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertFeedProductsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertFeedProductsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertFeedProductsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateFeedWithBodyWithResponse Create a feed
//
// Creates a feed resource and returns server-managed metadata for the new feed.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /feeds (the `CreateFeed` operationId).
func (c *ClientWithResponses) CreateFeedWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateFeedResponse, error) {
	rsp, err := c.CreateFeedWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFeedResponse(rsp)
}

// CreateFeedWithResponse Create a feed
//
// Creates a feed resource and returns server-managed metadata for the new feed.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /feeds (the `CreateFeed` operationId).
func (c *ClientWithResponses) CreateFeedWithResponse(ctx context.Context, body CreateFeedJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateFeedResponse, error) {
	rsp, err := c.CreateFeed(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateFeedResponse(rsp)
}

// GetFeedWithResponse Retrieve feed metadata
//
// Returns server-managed metadata for the specified feed.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /feeds/{id} (the `GetFeed` operationId).
func (c *ClientWithResponses) GetFeedWithResponse(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*GetFeedResponse, error) {
	rsp, err := c.GetFeed(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFeedResponse(rsp)
}

// GetFeedProductsWithResponse Retrieve products for a feed
//
// Returns the full current product set for the specified feed.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /feeds/{id}/products (the `GetFeedProducts` operationId).
func (c *ClientWithResponses) GetFeedProductsWithResponse(ctx context.Context, id FeedId, reqEditors ...RequestEditorFn) (*GetFeedProductsResponse, error) {
	rsp, err := c.GetFeedProducts(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFeedProductsResponse(rsp)
}

// UpsertFeedProductsWithBodyWithResponse Upsert products for a feed
//
// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
func (c *ClientWithResponses) UpsertFeedProductsWithBodyWithResponse(ctx context.Context, id FeedId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertFeedProductsResponse, error) {
	rsp, err := c.UpsertFeedProductsWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertFeedProductsResponse(rsp)
}

// UpsertFeedProductsWithResponse Upsert products for a feed
//
// Upserts products into the specified feed by `Product.id`. Products omitted from the request remain unchanged.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /feeds/{id}/products (the `UpsertFeedProducts` operationId).
func (c *ClientWithResponses) UpsertFeedProductsWithResponse(ctx context.Context, id FeedId, body UpsertFeedProductsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertFeedProductsResponse, error) {
	rsp, err := c.UpsertFeedProducts(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertFeedProductsResponse(rsp)
}

// ParseCreateFeedResponse parses an HTTP response from a CreateFeedWithResponse call
func ParseCreateFeedResponse(rsp *http.Response) (*CreateFeedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateFeedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest FeedMetadata
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetFeedResponse parses an HTTP response from a GetFeedWithResponse call
func ParseGetFeedResponse(rsp *http.Response) (*GetFeedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFeedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FeedMetadata
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetFeedProductsResponse parses an HTTP response from a GetFeedProductsWithResponse call
func ParseGetFeedProductsResponse(rsp *http.Response) (*GetFeedProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFeedProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpsertFeedProductsResponse parses an HTTP response from a UpsertFeedProductsWithResponse call
func ParseUpsertFeedProductsResponse(rsp *http.Response) (*UpsertFeedProductsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertFeedProductsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpsertProductsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
