// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.

package acpauthentication

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActionType.
const (
	ActionTypeChallenge   ActionType = "challenge"
	ActionTypeFingerprint ActionType = "fingerprint"
)

// Valid indicates whether the value is a known member of the ActionType enum.
func (e ActionType) Valid() bool {
	switch e {
	case ActionTypeChallenge:
		return true
	case ActionTypeFingerprint:
		return true
	default:
		return false
	}
}

// Defines values for ChannelType.
const (
	Browser ChannelType = "browser"
)

// Valid indicates whether the value is a known member of the ChannelType enum.
func (e ChannelType) Valid() bool {
	switch e {
	case Browser:
		return true
	default:
		return false
	}
}

// Defines values for DelegateAuthenticationAuthenticateRequestFingerprintCompletion.
const (
	N DelegateAuthenticationAuthenticateRequestFingerprintCompletion = "N"
	U DelegateAuthenticationAuthenticateRequestFingerprintCompletion = "U"
	Y DelegateAuthenticationAuthenticateRequestFingerprintCompletion = "Y"
)

// Valid indicates whether the value is a known member of the DelegateAuthenticationAuthenticateRequestFingerprintCompletion enum.
func (e DelegateAuthenticationAuthenticateRequestFingerprintCompletion) Valid() bool {
	switch e {
	case N:
		return true
	case U:
		return true
	case Y:
		return true
	default:
		return false
	}
}

// Defines values for DelegateAuthenticationSessionBaseStatus.
const (
	DelegateAuthenticationSessionBaseStatusActionRequired     DelegateAuthenticationSessionBaseStatus = "action_required"
	DelegateAuthenticationSessionBaseStatusAttempted          DelegateAuthenticationSessionBaseStatus = "attempted"
	DelegateAuthenticationSessionBaseStatusAuthenticated      DelegateAuthenticationSessionBaseStatus = "authenticated"
	DelegateAuthenticationSessionBaseStatusChallengeAbandoned DelegateAuthenticationSessionBaseStatus = "challenge_abandoned"
	DelegateAuthenticationSessionBaseStatusExpired            DelegateAuthenticationSessionBaseStatus = "expired"
	DelegateAuthenticationSessionBaseStatusNotAuthenticated   DelegateAuthenticationSessionBaseStatus = "not_authenticated"
	DelegateAuthenticationSessionBaseStatusNotSupported       DelegateAuthenticationSessionBaseStatus = "not_supported"
	DelegateAuthenticationSessionBaseStatusPending            DelegateAuthenticationSessionBaseStatus = "pending"
	DelegateAuthenticationSessionBaseStatusRejected           DelegateAuthenticationSessionBaseStatus = "rejected"
	DelegateAuthenticationSessionBaseStatusUnavailable        DelegateAuthenticationSessionBaseStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the DelegateAuthenticationSessionBaseStatus enum.
func (e DelegateAuthenticationSessionBaseStatus) Valid() bool {
	switch e {
	case DelegateAuthenticationSessionBaseStatusActionRequired:
		return true
	case DelegateAuthenticationSessionBaseStatusAttempted:
		return true
	case DelegateAuthenticationSessionBaseStatusAuthenticated:
		return true
	case DelegateAuthenticationSessionBaseStatusChallengeAbandoned:
		return true
	case DelegateAuthenticationSessionBaseStatusExpired:
		return true
	case DelegateAuthenticationSessionBaseStatusNotAuthenticated:
		return true
	case DelegateAuthenticationSessionBaseStatusNotSupported:
		return true
	case DelegateAuthenticationSessionBaseStatusPending:
		return true
	case DelegateAuthenticationSessionBaseStatusRejected:
		return true
	case DelegateAuthenticationSessionBaseStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for DelegateAuthenticationSessionWithResultStatus.
const (
	DelegateAuthenticationSessionWithResultStatusActionRequired     DelegateAuthenticationSessionWithResultStatus = "action_required"
	DelegateAuthenticationSessionWithResultStatusAttempted          DelegateAuthenticationSessionWithResultStatus = "attempted"
	DelegateAuthenticationSessionWithResultStatusAuthenticated      DelegateAuthenticationSessionWithResultStatus = "authenticated"
	DelegateAuthenticationSessionWithResultStatusChallengeAbandoned DelegateAuthenticationSessionWithResultStatus = "challenge_abandoned"
	DelegateAuthenticationSessionWithResultStatusExpired            DelegateAuthenticationSessionWithResultStatus = "expired"
	DelegateAuthenticationSessionWithResultStatusNotAuthenticated   DelegateAuthenticationSessionWithResultStatus = "not_authenticated"
	DelegateAuthenticationSessionWithResultStatusNotSupported       DelegateAuthenticationSessionWithResultStatus = "not_supported"
	DelegateAuthenticationSessionWithResultStatusPending            DelegateAuthenticationSessionWithResultStatus = "pending"
	DelegateAuthenticationSessionWithResultStatusRejected           DelegateAuthenticationSessionWithResultStatus = "rejected"
	DelegateAuthenticationSessionWithResultStatusUnavailable        DelegateAuthenticationSessionWithResultStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the DelegateAuthenticationSessionWithResultStatus enum.
func (e DelegateAuthenticationSessionWithResultStatus) Valid() bool {
	switch e {
	case DelegateAuthenticationSessionWithResultStatusActionRequired:
		return true
	case DelegateAuthenticationSessionWithResultStatusAttempted:
		return true
	case DelegateAuthenticationSessionWithResultStatusAuthenticated:
		return true
	case DelegateAuthenticationSessionWithResultStatusChallengeAbandoned:
		return true
	case DelegateAuthenticationSessionWithResultStatusExpired:
		return true
	case DelegateAuthenticationSessionWithResultStatusNotAuthenticated:
		return true
	case DelegateAuthenticationSessionWithResultStatusNotSupported:
		return true
	case DelegateAuthenticationSessionWithResultStatusPending:
		return true
	case DelegateAuthenticationSessionWithResultStatusRejected:
		return true
	case DelegateAuthenticationSessionWithResultStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	DuplicateRequest    ErrorCode = "duplicate_request"
	IdempotencyConflict ErrorCode = "idempotency_conflict"
	InvalidCard         ErrorCode = "invalid_card"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case DuplicateRequest:
		return true
	case IdempotencyConflict:
		return true
	case InvalidCard:
		return true
	default:
		return false
	}
}

// Defines values for ErrorType.
const (
	InvalidRequest     ErrorType = "invalid_request"
	ProcessingError    ErrorType = "processing_error"
	RateLimitExceeded  ErrorType = "rate_limit_exceeded"
	ServiceUnavailable ErrorType = "service_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorType enum.
func (e ErrorType) Valid() bool {
	switch e {
	case InvalidRequest:
		return true
	case ProcessingError:
		return true
	case RateLimitExceeded:
		return true
	case ServiceUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for FlowPreferenceChallengeType.
const (
	Mandated  FlowPreferenceChallengeType = "mandated"
	Preferred FlowPreferenceChallengeType = "preferred"
)

// Valid indicates whether the value is a known member of the FlowPreferenceChallengeType enum.
func (e FlowPreferenceChallengeType) Valid() bool {
	switch e {
	case Mandated:
		return true
	case Preferred:
		return true
	default:
		return false
	}
}

// Defines values for FlowPreferenceType.
const (
	FlowPreferenceTypeChallenge    FlowPreferenceType = "challenge"
	FlowPreferenceTypeFrictionless FlowPreferenceType = "frictionless"
)

// Valid indicates whether the value is a known member of the FlowPreferenceType enum.
func (e FlowPreferenceType) Valid() bool {
	switch e {
	case FlowPreferenceTypeChallenge:
		return true
	case FlowPreferenceTypeFrictionless:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethodType.
const (
	Card PaymentMethodType = "card"
)

// Valid indicates whether the value is a known member of the PaymentMethodType enum.
func (e PaymentMethodType) Valid() bool {
	switch e {
	case Card:
		return true
	default:
		return false
	}
}

// Action Describes browser action required
type Action struct {
	// Challenge Configuration for cardholder challenge interaction.
	Challenge *ChallengeAction `json:"challenge,omitempty"`

	// Fingerprint Configuration for browser fingerprinting via iframe.
	Fingerprint *FingerprintAction `json:"fingerprint,omitempty"`

	// Type Category of action.
	Type  ActionType `json:"type"`
	union json.RawMessage
}

// ActionType Category of action.
type ActionType string

// Action0 defines model for Action.0.
type Action0 struct {
	Type interface{} `json:"type,omitempty"`
}

// Action1 defines model for Action.1.
type Action1 struct {
	Type interface{} `json:"type,omitempty"`
}

// Address Physical address schema for shopper or shipping.
type Address struct {
	// City City name.
	City string `json:"city"`

	// Country ISO-3166-1 alpha-2
	Country string `json:"country"`

	// LineOne Street address line 1.
	LineOne string `json:"line_one"`

	// LineTwo Street address line 2.
	LineTwo *string `json:"line_two,omitempty"`

	// Name Full name of the recipient.
	Name string `json:"name"`

	// PostalCode Postal code or ZIP code.
	PostalCode string `json:"postal_code"`

	// State ISO-3166-2 where applicable
	State string `json:"state"`
}

// Amount Monetary amount for the authentication request.
type Amount struct {
	// Currency ISO 4217 currency code
	Currency string `json:"currency"`

	// Value Amount in minor units (e.g., 1000 = €10.00)
	Value int `json:"value"`
}

// AuthenticationResult The finalized 3DS authentication data.
type AuthenticationResult struct {
	// AuthenticationValue Authentication value (CAVV)
	AuthenticationValue *string `json:"authentication_value,omitempty"`

	// CardholderInfo Message to display to cardholder
	CardholderInfo *string `json:"cardholder_info,omitempty"`

	// ElectronicCommerceIndicator Electronic Commerce Indicator (ECI)
	ElectronicCommerceIndicator *string `json:"electronic_commerce_indicator,omitempty"`

	// ThreeDsCryptogram Authentication cryptogram (CAVV/AAV)
	ThreeDsCryptogram *string `json:"three_ds_cryptogram,omitempty"`

	// ThreeDsServerTransId 3DS Server transaction ID
	ThreeDsServerTransId string `json:"three_ds_server_trans_id"`

	// TransStatus Transaction status (Y, N, A, U, R, etc.)
	TransStatus string `json:"trans_status"`

	// TransStatusReason Reason code for trans_status
	TransStatusReason *string `json:"trans_status_reason,omitempty"`

	// TransactionId Directory Server transaction ID
	TransactionId string `json:"transaction_id"`

	// Version 3DS protocol version (e.g., "2.2.0")
	Version string `json:"version"`
}

// BrowserInfo Detailed browser metadata for 3DS2.
type BrowserInfo struct {
	// AcceptHeader HTTP Accept header from the browser
	AcceptHeader string `json:"accept_header"`

	// ColorDepth Screen color depth (required if javascript_enabled is true)
	ColorDepth *int `json:"color_depth,omitempty"`

	// IpAddress IP address of the browser
	IpAddress string `json:"ip_address"`

	// JavaEnabled Whether Java is enabled (required if javascript_enabled is true)
	JavaEnabled *bool `json:"java_enabled,omitempty"`

	// JavascriptEnabled Whether JavaScript is enabled
	JavascriptEnabled bool `json:"javascript_enabled"`

	// Language IETF BCP 47 language tag
	Language string `json:"language"`

	// ScreenHeight Screen height in pixels (required if javascript_enabled is true)
	ScreenHeight *int `json:"screen_height,omitempty"`

	// ScreenWidth Screen width in pixels (required if javascript_enabled is true)
	ScreenWidth *int `json:"screen_width,omitempty"`

	// TimezoneOffset Timezone offset in minutes (required if javascript_enabled is true)
	TimezoneOffset *int `json:"timezone_offset,omitempty"`

	// UserAgent Browser user agent string
	UserAgent string `json:"user_agent"`
}

// ChallengeAction Configuration for cardholder challenge interaction.
type ChallengeAction struct {
	// AcsTransId ACS transaction identifier
	AcsTransId string `json:"acs_trans_id"`

	// AcsUrl URL to POST challenge request to
	AcsUrl string `json:"acs_url"`

	// MessageVersion 3DS protocol version (e.g., "2.2.0")
	MessageVersion string `json:"message_version"`

	// ThreeDsServerTransId 3DS Server transaction identifier
	ThreeDsServerTransId string `json:"three_ds_server_trans_id"`
}

// Channel Defines the platform/medium for the session.
type Channel struct {
	// Browser Detailed browser metadata for 3DS2.
	Browser BrowserInfo `json:"browser"`

	// Type Channel type
	Type ChannelType `json:"type"`
}

// ChannelType Channel type
type ChannelType string

// DelegateAuthenticationAuthenticateRequest Request body to submit fingerprint result and trigger AReq.
type DelegateAuthenticationAuthenticateRequest struct {
	// ChallengeNotificationUrl URL for challenge result callback
	ChallengeNotificationUrl *string `json:"challenge_notification_url,omitempty"`

	// Channel Defines the platform/medium for the session.
	Channel *Channel `json:"channel,omitempty"`

	// CheckoutSessionId Checkout session identifier
	CheckoutSessionId *string `json:"checkout_session_id,omitempty"`

	// FingerprintCompletion Result of the 3DS Method fingerprint:
	// - Y: Completed successfully
	// - N: Timeout/not completed
	// - U: Unavailable/not performed
	FingerprintCompletion DelegateAuthenticationAuthenticateRequestFingerprintCompletion `json:"fingerprint_completion"`

	// ShopperDetails Identity and contact info for the shopper.
	ShopperDetails *ShopperDetails `json:"shopper_details,omitempty"`
}

// DelegateAuthenticationAuthenticateRequestFingerprintCompletion Result of the 3DS Method fingerprint:
// - Y: Completed successfully
// - N: Timeout/not completed
// - U: Unavailable/not performed
type DelegateAuthenticationAuthenticateRequestFingerprintCompletion string

// DelegateAuthenticationCreateRequest Request body to initialize an authentication session.
type DelegateAuthenticationCreateRequest struct {
	// AcquirerDetails Object containing acquirer data used for AReq construction.
	// **Recommended:** To ensure the AReq matches the final Authorization, especially when using different authentication and payment providers.
	AcquirerDetails *struct {
		// AcquirerBin The Acquirer BIN.
		AcquirerBin string `json:"acquirer_bin"`

		// AcquirerCountry Two-letter ISO 3166-1 alpha-2 country code.
		AcquirerCountry string `json:"acquirer_country"`

		// AcquirerMerchantId The Merchant ID assigned by the acquirer.
		AcquirerMerchantId string `json:"acquirer_merchant_id"`

		// MerchantName Merchant name assigned by the acquirer.
		MerchantName string `json:"merchant_name"`

		// RequestorId 3DS Requestor ID (if required by directory server).
		RequestorId *string `json:"requestor_id,omitempty"`
	} `json:"acquirer_details,omitempty"`

	// Amount Monetary amount for the authentication request.
	Amount Amount `json:"amount"`

	// ChallengeNotificationUrl URL for challenge result callback
	ChallengeNotificationUrl *string `json:"challenge_notification_url,omitempty"`

	// Channel Defines the platform/medium for the session.
	Channel *Channel `json:"channel,omitempty"`

	// CheckoutSessionId Checkout session identifier
	CheckoutSessionId *string `json:"checkout_session_id,omitempty"`

	// FlowPreference Preference for the 3DS authentication flow. Clients MAY request a preference,
	// but issuers ultimately decide the actual flow.
	FlowPreference *FlowPreference `json:"flow_preference,omitempty"`

	// MerchantId Merchant identifier
	MerchantId string `json:"merchant_id"`

	// PaymentMethod Card information for the authentication session.
	PaymentMethod PaymentMethod `json:"payment_method"`

	// ShopperDetails Identity and contact info for the shopper.
	ShopperDetails *ShopperDetails `json:"shopper_details,omitempty"`
}

// DelegateAuthenticationSession Response object representing a standard session state.
type DelegateAuthenticationSession = DelegateAuthenticationSessionBase

// DelegateAuthenticationSessionBase Base properties for an authentication session response.
type DelegateAuthenticationSessionBase struct {
	// Action Describes browser action required
	Action *Action `json:"action,omitempty"`

	// AuthenticationSessionId Session ID for subsequent requests
	AuthenticationSessionId string `json:"authentication_session_id"`

	// Status Current state of the session.
	// - action_required: Browser action needed.
	// - pending: Awaiting completion.
	// - not_supported: Method not available.
	Status DelegateAuthenticationSessionBaseStatus `json:"status"`
}

// DelegateAuthenticationSessionBaseStatus Current state of the session.
// - action_required: Browser action needed.
// - pending: Awaiting completion.
// - not_supported: Method not available.
type DelegateAuthenticationSessionBaseStatus string

// DelegateAuthenticationSessionWithResult Response object containing the full session state and final result.
type DelegateAuthenticationSessionWithResult struct {
	// Action Describes browser action required
	Action *Action `json:"action,omitempty"`

	// AuthenticationResult The finalized 3DS authentication data.
	AuthenticationResult *AuthenticationResult `json:"authentication_result,omitempty"`

	// AuthenticationSessionId Session ID for subsequent requests
	AuthenticationSessionId string `json:"authentication_session_id"`

	// Status Current state of the session.
	// - action_required: Browser action needed.
	// - pending: Awaiting completion.
	// - not_supported: Method not available.
	Status DelegateAuthenticationSessionWithResultStatus `json:"status"`
}

// DelegateAuthenticationSessionWithResultStatus Current state of the session.
// - action_required: Browser action needed.
// - pending: Awaiting completion.
// - not_supported: Method not available.
type DelegateAuthenticationSessionWithResultStatus string

// Error Structured error response.
type Error struct {
	// Code Specific error sub-code.
	Code ErrorCode `json:"code"`

	// Message Detailed error description.
	Message string `json:"message"`

	// Param RFC 9535 JSONPath (optional)
	Param *string `json:"param,omitempty"`

	// Type Category of error.
	Type ErrorType `json:"type"`
}

// ErrorCode Specific error sub-code.
type ErrorCode string

// ErrorType Category of error.
type ErrorType string

// FingerprintAction Configuration for browser fingerprinting via iframe.
type FingerprintAction struct {
	// ThreeDsMethodUrl URL to POST fingerprint data to via hidden iframe
	ThreeDsMethodUrl string `json:"three_ds_method_url"`

	// ThreeDsServerTransId 3DS Server transaction ID
	ThreeDsServerTransId string `json:"three_ds_server_trans_id"`
}

// FlowPreference Preference for the 3DS authentication flow. Clients MAY request a preference,
// but issuers ultimately decide the actual flow.
type FlowPreference struct {
	// Challenge Preference details for a challenge flow.
	Challenge *struct {
		// Type Subtype of challenge preference
		Type *FlowPreferenceChallengeType `json:"type,omitempty"`
	} `json:"challenge,omitempty"`

	// Frictionless Details about the requested frictionless flow
	Frictionless *map[string]interface{} `json:"frictionless,omitempty"`

	// Type Type of flow requested
	Type FlowPreferenceType `json:"type"`
}

// FlowPreferenceChallengeType Subtype of challenge preference
type FlowPreferenceChallengeType string

// FlowPreferenceType Type of flow requested
type FlowPreferenceType string

// PaymentMethod Card information for the authentication session.
type PaymentMethod struct {
	// ExpMonth Expiry month (01-12)
	ExpMonth string `json:"exp_month"`

	// ExpYear Expiry year (4 digits)
	ExpYear string `json:"exp_year"`

	// Name Cardholder name
	Name string `json:"name"`

	// Number Card number (PAN)
	Number string `json:"number"`

	// Type Payment method type
	Type PaymentMethodType `json:"type"`
}

// PaymentMethodType Payment method type
type PaymentMethodType string

// ShopperDetails Identity and contact info for the shopper.
type ShopperDetails struct {
	// Address Physical address schema for shopper or shipping.
	Address *Address `json:"address,omitempty"`

	// Email Shopper email
	Email *openapi_types.Email `json:"email,omitempty"`

	// Name Shopper name
	Name *string `json:"name,omitempty"`

	// PhoneNumber Shopper phone number
	PhoneNumber *string `json:"phone_number,omitempty"`
}

// APIVersion defines model for APIVersion.
type APIVersion = string

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage = string

// Authorization defines model for Authorization.
type Authorization = string

// ContentType defines model for ContentType.
type ContentType = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// RequestId defines model for RequestId.
type RequestId = string

// Signature defines model for Signature.
type Signature = string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UserAgent defines model for UserAgent.
type UserAgent = string

// CreateAuthenticationSessionParams defines parameters for CreateAuthenticationSession.
type CreateAuthenticationSessionParams struct {
	Authorization  Authorization   `json:"Authorization"`
	ContentType    ContentType     `json:"Content-Type"`
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
	UserAgent      *UserAgent      `json:"User-Agent,omitempty"`
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
	RequestId      *RequestId      `json:"Request-Id,omitempty"`
	Signature      *Signature      `json:"Signature,omitempty"`
	Timestamp      *Timestamp      `json:"Timestamp,omitempty"`
	APIVersion     APIVersion      `json:"API-Version"`
}

// GetAuthenticationSessionParams defines parameters for GetAuthenticationSession.
type GetAuthenticationSessionParams struct {
	Authorization  Authorization   `json:"Authorization"`
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
	UserAgent      *UserAgent      `json:"User-Agent,omitempty"`
	RequestId      *RequestId      `json:"Request-Id,omitempty"`
	Signature      *Signature      `json:"Signature,omitempty"`
	Timestamp      *Timestamp      `json:"Timestamp,omitempty"`
	APIVersion     APIVersion      `json:"API-Version"`
}

// AuthenticateSessionParams defines parameters for AuthenticateSession.
type AuthenticateSessionParams struct {
	Authorization  Authorization   `json:"Authorization"`
	ContentType    ContentType     `json:"Content-Type"`
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
	UserAgent      *UserAgent      `json:"User-Agent,omitempty"`
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
	RequestId      *RequestId      `json:"Request-Id,omitempty"`
	Signature      *Signature      `json:"Signature,omitempty"`
	Timestamp      *Timestamp      `json:"Timestamp,omitempty"`
	APIVersion     APIVersion      `json:"API-Version"`
}

// CreateAuthenticationSessionJSONRequestBody defines body for CreateAuthenticationSession for application/json ContentType.
type CreateAuthenticationSessionJSONRequestBody = DelegateAuthenticationCreateRequest

// AuthenticateSessionJSONRequestBody defines body for AuthenticateSession for application/json ContentType.
type AuthenticateSessionJSONRequestBody = DelegateAuthenticationAuthenticateRequest

// AsAction0 returns the union data inside the Action as a Action0
func (t Action) AsAction0() (Action0, error) {
	var body Action0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAction0 overwrites any union data inside the Action as the provided Action0
func (t *Action) FromAction0(v Action0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAction0 performs a merge with any union data inside the Action, using the provided Action0
func (t *Action) MergeAction0(v Action0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAction1 returns the union data inside the Action as a Action1
func (t Action) AsAction1() (Action1, error) {
	var body Action1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAction1 overwrites any union data inside the Action as the provided Action1
func (t *Action) FromAction1(v Action1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAction1 performs a merge with any union data inside the Action, using the provided Action1
func (t *Action) MergeAction1(v Action1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Action) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Challenge != nil {
		object["challenge"], err = json.Marshal(t.Challenge)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challenge': %w", err)
		}
	}

	if t.Fingerprint != nil {
		object["fingerprint"], err = json.Marshal(t.Fingerprint)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fingerprint': %w", err)
		}
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Action) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challenge"]; found {
		err = json.Unmarshal(raw, &t.Challenge)
		if err != nil {
			return fmt.Errorf("error reading 'challenge': %w", err)
		}
	}

	if raw, found := object["fingerprint"]; found {
		err = json.Unmarshal(raw, &t.Fingerprint)
		if err != nil {
			return fmt.Errorf("error reading 'fingerprint': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	return err
}
